### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by UweZiegenhagen** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#100]
Hallo liebe Mitschreiberlinge,

das Jahr nähert sich dem Ende und ich möchte mal nach dem Status fragen. Bis wann denkt ihr, dass ihr eure Teile finalisieren könnt?

Ich möchte spätestens Anfang des Jahres mit meinem Teil weitermachen.

**Comment by thomas-hilarius-meyer** [comment]
Lieber Uwe,
(und Ihr lieben andern...),

also, bei mir ist es so: Ich habe es tatsächlich hingekriegt, meine
Doktorarbeit als "Vorrangprojekt" soweit hinzukriegen, dass ich sie Ende
Januar abgeben kann. Und dann wollte ich LFGW fertigbekommen...

Ich wünsche Euch schöne Feiertage und alles Gute im nächsten Jahr!

Herzliche Grüße
Thomas


Am 23. Dezember 2017 um 18:33 schrieb Uwe Ziegenhagen <
notifications@github.com>:

**Comment by baem2** [comment]
Meine Abschnitte sind einigermaßen fertig, ich könnte sie aber für den Abschluß noch polieren und an anderen Ecken und Enden weitrehelfen.

Frohe Weihnacht!

**Comment by AKielhorn** [comment]
Ich benötige für ein anderes Projekt gerade eine Literaturverwaltung.
In dem Kapitel gibt es ein paar kosmetische Probleme,
ich werd mir das in den nächsten Tagen mal ansehen und korrigieren.

Axel

**Comment by koppor** [comment]
@AKielhorn bezogen auf die Literaturverwaltung. Evtl. kann hier das JabRef-Handbuch helfen? https://manuals.jabref.org/JabRef-UserManual_de.pdf. Der LaTeX-Quelltext ist bei https://github.com/JabRef/manuals.jabref.org/tree/master/de versioniert. Updates sehr willkommen!

**Comment by baem2** [comment]
Und weiter geht's in #119.
