### ISSUE TITLE
Stefan W Bug 1: Schriftarten mit besonderen Anforderungen

### ISSUE THREAD

**Issue by UweZiegenhagen** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#105]
Stefan W hat mir einige Bugs im Skript geschickt:

Im PDF in Abschnitt 2.6.4 "Schriftarten mit besonderen Anforderungen" werden die alten deutschen Schriften vorgestellt. Leider sind in den Beispieltexten die Umlaute abhanden gekommen.

**Comment by AKielhorn** [comment]
Duplikat von #96.

Erledigt.
