### ISSUE TITLE
Huch!

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#11]
Vielen Dank für die vielen Korrekturen und Verbesserungen, aber hier sind mir zwei Sachen aufgefallen, die mich erstaunen:

* Parallele Texte S. 50
* alle Beispiele mit Quelltext und Ausgabe parallel

Was ist denn da passiert? Seltsam...

**Comment by LukasCBossert** [comment]
Die Sprachen habe ich nun global definiert, ansonsten war die Ausgabe in den Dateien unterschiedlich. 

```
\documentclass[%
ibycus,polutonikogreek,english,french,ngerman,%global definiert!
   %%%draft=false,%
   fontsize=11pt,%
   paper=17cm:24cm,%
   DIV=13,%
   pagesize%
   ]{scrbook}
```
