### ISSUE TITLE
Overfull hbox im griechischen Beispieltext

### ISSUE THREAD

**Issue by AKielhorn** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#113]
Einige Beispieltexte im Kapitel 5 sind zu breit.

Da mein griechisch nicht gut genug ist, möchte ich da nichts dran ändern.

**Comment by baem2** [comment]
Oha, Kapitel 5, das bin ja ich!

**Comment by baem2** [comment]
Ich habe den Verdacht, daß das daran liegt, daß das reledmacbsp den einen parindent hat und dadurch zu weit nach rechts geschoben wird. Kann das vielleicht jemand reparieren, der diese technicalities besser versteht?

**Comment by AKielhorn** [comment]
> Am 19.12.2019 um 22:02 schrieb Philipp <notifications@github.com>:
> 
> Ich habe den Verdacht, daß das daran liegt, daß das reledmacbsp den einen parindent hat und dadurch zu weit nach rechts geschoben wird. Kann das vielleicht jemand reparieren, der diese technicalities besser versteht?

Die Wörter sind alle mit ~ verbunden.

Wenn ich im Beispiel 5.11 ein paar davon in Leerzeichen ändere, dann passt das.
Der Text müsste nur sinnvoll auf eine kürzere Zeilenlänge gebracht werden.
Dazu wäre es natürlich praktisch ihn zu verstehen.
Am besten so, das der Zeilenlauf in allen Beispielen gleich ist.

\begin{lfgwcode}{}
\msdata{G§~§T§~§U§~§V}§\null§Τῆς§~§\vari{§\null§Κιλικίας}{§\null§Πισιδίας§~§V}§~§δὲ§ §τῆς§ §\vari{§\null§ἔξω}
•{\emph{del.}§~§G}
§\null§τοῦ§~§Ταύρου§~§ἡ§~§μὲν§~§λέγεται§~§τραχεῖα§~§ἡ§~§δὲ§~§πεδιάς;
§\null§τραχεῖα§~§μέν,§~§ἧς§~§\quell[§\null§ἡ§~§\dots{}§~§ἐστι]{§\null§ἡ§~§παραλία§ §\alteSeite{}§~§στενή§~§ἐστι}%
{Konon§~§Paraliotes,§~§Κοσμογραφία§~§VI§~§7}§~§καὶ§~§οὐδὲν
\vari{§\null§ἢ§~§σπανίως}{§\null§ἢ§~§σπανιαίτερον§~§V§~§U;§ §\emph{del.}§~§T}§~§ἔχει§~§τι§ ∞§χωρίον
\msdata{G§~§U}§\null§ἐπίπεδον,§~§καὶ§~§ἔτι§~§ἧς§~§ὑπέρκειται§~§ὁ§~§Ταῦρος§~§οἰκούμενος§ §κακῶς§ ∞§μέχρι§ §καὶ§~§τῶν
§\null§προσβόρρων§~§πλευρῶν§~§τῶν§~§περὶ§~§Ἴσαυρα§~§καὶ§~§τοὺς§~§Ὁμοναδέας§~§μέχρι§~§τῆς§ ∞§Πισιδίας;
\end{lfgwcode}

• Manueller Umbruch von mir, neue Zeilennummer.
∞ Automatischer Umbruch, keine neue Zeilennummer

Das T 269 ist ein \ledsidenote

Mit
\newcommand\alteSeite{{|\ledsidenote{\quad\emph{T}~\thealteSeite}}}%stepcounter machen wir hier nicht, sonst zählt er ja immer weiter …
könnte man den Text aus dem grauen Hintergrund rausschieben.
Sieht dann fast aus wie gewollt.

**Comment by baem2** [comment]
Das §~§-Kauderwelsch hat seinen Grund hier: #77 – Das meckert er bei mir aber gar nicht an (also keine overfullbox), die betrifft bei mir Z. 171; 215; 278 etc. Das sind die reledmacbsp.

**Comment by AKielhorn** [comment]
> Am 19.12.2019 um 23:23 schrieb Philipp <notifications@github.com>:
> 
> Das §~§-Kauderwelsch hat seinen Grund hier: #77 – Das meckert er bei mir aber gar nicht an (also keine overfullbox), die betrifft bei mir Z. 171; 215; 278 etc. Das sind die reledmacbsp.

Aber der Text passt nicht in die graue Box.
Schon Beispiel 5.2 fällt aus dem Rahmen.
Beispiel 5.4 sogar aus dem Beschnitt.

Da es keine Leerzeichen gibt, erfolgt auch kein Umbruch.
Daher bin ich für einen manuellen Umbruch, sodass Beispiel 5.11 im Rahmen bleibt.
Alle anderen Beispiele erhalten dann den gleichen Umbruch damit gleiche Wörter in der gleichen Zeile stehen.

Ist das ein sinnvoller Umbruch?
Vor lauter § kann ich den Text kaum lesen.

\begin{lfgwcode}{}
\msdata{G§~§T§~§U§~§V}§\null§Τῆς§~§\vari{§\null§Κιλικίας}{§\null§Πισιδίας§~§V}§~§δὲ§~§τῆς§ 
§\vari{§\null§ἔξω}{\emph{del.}§~§G}
§\null§τοῦ§~§Ταύρου§~§ἡ§~§μὲν§~§λέγεται§~§τραχεῖα§~§ἡ§~§δὲ§~§πεδιάς;
§\null§τραχεῖα§~§μέν,§~§ἧς§~§\quell[§\null§ἡ§~§\dots{}§~§ἐστι]{§\null§ἡ§~§παραλία§ 
§\alteSeite{}§~§στενή§~§ἐστι}%
{Konon§~§Paraliotes,§~§Κοσμογραφία§~§VI§~§7}§~§καὶ§~§οὐδὲν
\vari{§\null§ἢ§~§σπανίως}{§\null§ἢ§~§σπανιαίτερον§~§V§~§U;§§
\emph{del.}§~§T}§~§ἔχει§~§τι§ §χωρίον
\msdata{G§~§U}§\null§ἐπίπεδον,§~§καὶ§~§ἔτι§~§ἧς§~§ὑπέρκειται§~§ὁ§~§Ταῦρος§~§οἰκούμενος
§~§κακῶς§~§μέχρι§~§καὶ§~§τῶν
§\null§προσβόρρων§~§πλευρῶν§~§τῶν§~§περὶ§~§Ἴσαυρα§~§καὶ§~§τοὺς§~§Ὁμοναδέας§~§μέχρι
§~§τῆς§~§Πισιδίας;
\end{lfgwcode}

Oder sollte man lieber nach reledmac Befehlen gliedern?
Muss ich vor oder hinter dem § trennen?

\begin{lfgwcode}{}
\msdata{G§~§T§~§U§~§V}§\null§Τῆς§~§
  \vari{§\null§Κιλικίας}
       {§\null§Πισιδίας§~§V}
       §~§δὲ§~§τῆς§ 
  §\vari{§\null§ἔξω}
       {\emph{del.}§~§G}
       §\null§τοῦ§~§Ταύρου§~§ἡ§~§μὲν§~§λέγεται§~§τραχεῖα§~§ἡ§~§δὲ§~§πεδιάς;
  §\null§τραχεῖα§~§μέν,§~§ἧς§~§
  \quell[§\null§ἡ§~§\dots{}§~§ἐστι]
        {§\null§ἡ§~§παραλία§~§\alteSeite{}§~§στενή§~§ἐστι}%
        {Konon§~§Paraliotes,§~§Κοσμογραφία§~§VI§~§7}§~§καὶ§~§οὐδὲν
  \vari{§\null§ἢ§~§σπανίως}
       {§\null§ἢ§~§σπανιαίτερον§~§V§~§U;§§\emph{del.}§~§T}
       §~§ἔχει§~§τι§ §χωρίον
\msdata{G§~§U}§\null§ἐπίπεδον,§~§καὶ§~§ἔτι§~§ἧς§~§ὑπέρκειται§~§ὁ§~§Ταῦρος§~§οἰκούμενος
  §~§κακῶς§~§μέχρι§~§καὶ§~§τῶν
  §\null§προσβόρρων§~§πλευρῶν§~§τῶν§~§περὶ§~§Ἴσαυρα§~§καὶ§~§τοὺς§~§Ὁμοναδέας§~§μέχρι
  §~§τῆς§~§Πισιδίας;
\end{lfgwcode}

Den linken Rand des Ausgabetextes kann man mit einem \noindent korrigieren.
Warum die Box jetzt breiter ist als der Quellcode kann ich nicht sagen.

Den Strabon in der environment-Definition zu verstecken ist übrigens auch nicht nett.
Ich komme vom Beispieltext nicht auf die angezeigte Ausgabe.

**Comment by AKielhorn** [comment]
Da habe ich den Fehler wohl an der falschen Stelle gesucht.

Ich schiebe das T 269 noch etwas weiter in den Rand, mache die reledmacbsp einen Hauch schmaler und füge ein paar \noindents ein.

Dann sieht das für mich sauber aus.
