### ISSUE TITLE
Herbsttagung

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#117]
Ihr Lieben,

ich will im September zur Herbsttagung nach Chemnitz fahren.
Kommt von Euch auch jemand?
Und sollten wir unser Projekt ein bisschen vorstellen?
Das Vortragsprogramm ist noch sooo leer...

LG
Thomas

**Comment by UweZiegenhagen** [comment]
Ich werde da sein. Gern.

**Comment by sieversMartin** [comment]
Hallo,

Ich werde ebenfalls dort sein.

Gruß
Martin

⁣Gesendet mit TypeApp ​

**Comment by thomas-hilarius-meyer** [comment]
Absolute Deadline ist Weihnachten.
Allerallerspätestens.
Aber wir sagen keine Jahreszahl...

Am 4. August 2018 um 20:22 schrieb Jürgen Fenn <notifications@github.com>:

**Comment by schneeschmelze** [comment]
Dann sage ich mal Weihnachten 2018. – Danke.

**Comment by thomas-hilarius-meyer** [comment]
@ Uwe und Martin:

Sollen wir dann zusammen das Projekt vorstellen?
Ich würde dann eine mail an mv59@dante.de schreiben.
Arbeitstitel: 
"LaTeX für Geisteswissenschaftler - Eine Einführung"

Wie wir den Titel genau verstehen (Ist "Einführung" unser Skript oder geht es tatsächlich um eine Einführung im Rahmen des Vortags?) können wir uns immer noch überlegen...

**Comment by UweZiegenhagen** [comment]
Gute Idee, gern

Von meinem iPhone gesendet

**Comment by UweZiegenhagen** [comment]
Ich fang mal mit der Folien-Vorlage in einem Unterverzeichnis an.

**Comment by schneeschmelze** [comment]
_Räusper_ … ich sage „Januar“, wenn das noch okay für euch wäre? Tut mir leid, dass es sich hinzieht… – Danke!
