### ISSUE TITLE
CircleCI

### ISSUE THREAD

**Issue by sieversMartin** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#118]
Hallo Thomas,

ich würde mich um die am Wochenende kurz angesprochene "Continuous Integration" kümmern. Dazu müsstest du mich aber wohl der Admin-Gruppe hinzufügen oder aber eine eigene Organisation für das Buch anlegen und die "Herausgeber" dort hinzufügen.

**Comment by sieversMartin** [comment]
Hmm, ich bin nicht sicher. Könntest du mich testweise unter "Settings->Collaborators" zum "Admin" machen. Dann schau ich mal, ob ich bei CircleCI weiterkomme.

**Comment by sieversMartin** [comment]
Der Punkt scheint in der Tat nur bei Organisationen zu funktionieren. Ich schau mir das nochmal in Ruhe an ...

**Comment by mscircleci** [comment]
So, ich habe jetzt mal einen sogenannten "Machine user" angelegt und bitte dich, diesen als Collaborator hinzuzufügen. Er heißt @mscircleci
Danke.

**Comment by thomas-hilarius-meyer** [comment]
erledigt...


Am Di., 18. Sep. 2018 um 17:50 Uhr schrieb mscircleci <
notifications@github.com>:

**Comment by mscircleci** [comment]
Hmm, ich sehe aber noch nur 10 Contributor. Ist das so richtig?

**Comment by mscircleci** [comment]
Einladung angenommen.

**Comment by sieversMartin** [comment]
Es bleibt leider dabei. Ohne Organisation keine Admin-Rolle und ohne Admin-Rolle keine CircleCI.

**Comment by koppor** [comment]
@thomas-hilarius-meyer wird sich bei GitHub actions anmelden --> https://github.com/features/actions

![grafik](https://user-images.githubusercontent.com/1366654/67139938-e8008180-f255-11e9-8a36-5a67a4d2aaaf.png)

Then, we can use https://github.com/dante-ev/latex-action

**Comment by thomas-hilarius-meyer** [comment]
erledigt.


Am Sa., 19. Okt. 2019 um 09:51 Uhr schrieb Oliver Kopp <
notifications@github.com>:
