### ISSUE TITLE
Exam

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#12]
Ich hatte in meinem ursprünglichen Plan ein Kapitel für die Erstellung von Prüfungen mit exam vorgesehen.

Denkt Ihr, dass das in diesem Rahmen gerechtfertigt ist?

An sich kommt es mir schon sinnvoll vor, wenn es natürlich nicht sooo spezifisch für den LaTeX-Einsatz in den Geisteswissenschaften ist.

Denkt Ihr, es wäre sinnvoll, Uwe Ziegenhagen zu fragen, ob er seinen DTK-Aufsatz beisteuern will?

**Comment by LukasCBossert** [comment]
Ich würde sagen: warum nicht. Solange man den Fokus auf die geisteswissenschaftlichen Belange dabei legt, kann man es integrieren.

**Comment by baem2** [comment]
@UweZiegenhagen, was hältst Du davon?

**Comment by UweZiegenhagen** [comment]
Ist doch schon integriert, ich will es nur noch vereinheitlichen und etwas mehr Richtung Geisteswissenschaften umbauen.
