### ISSUE TITLE
CI failure

### ISSUE THREAD

**Issue by AKielhorn** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#125]
Seit gestern wird bei jedem commit ein CI-Lauf gestartet.

Mein commit von gestern brachte mir heute einen "Run failed".
Als ich nachgesehen habe, musste ich feststellen, das auch die runs davor nicht durchgelaufen sind. Selbst der fa134ed, der ja meinen Fehler korrigieren sollte, lief nicht.

Bei mir lokal läuft das Dokument mit TeXLive 2018 problemlos durch,
mit TL 2019 gibt es irgendein Problem mit graphics, die Bilder werden nicht gefunden.

Welche Version wird für CI verwendet?

Axel

**Comment by koppor** [comment]
Täglich aktualisiertes TeXLive. https://github.com/dante-ev/docker-texlive. Dort wird jeden Tag das Image aktualisiert, damit auch alle CTAN Updates drin sind.

Mhhh, unter diesen Umständen sollt ich schauen, dass TL2018 verwendet wird...

**Comment by AKielhorn** [comment]
Besser wäre es natürlich, den Fehler mit 2019 zu beheben.
Ich bin am Wochenende wieder am Terminal, zur Zeit gerade auf Vorstellungstour. 

-- 
Von Hand geschrieben mit einem ArtPen.

**Comment by koppor** [comment]
latexmk meckert: `Maximum runs of pdflatex reached without getting stable files`. (Siehe https://github.com/thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler/commit/00768927f77acdab790d20b0f42bacd65ebd79ef/checks?check_suite_id=282210804)

Mit MiKTeX kann ich es lokal nicht probieren, da ich dort folgenden Fehler bekomme:

```
C:/MiKTeX/tex/latex/keystroke/keystroke.sty:171: LaTeX Error: File `keystroke_l
eft' not found.
```

Habe nun auf lualatex, biber, lualatex, lualatex umgestellt. Es kommt ein PDF raus. Jetzt fehlt "nur noch", dass das PDF auf `gh-pages` landet.

**Comment by koppor** [comment]
Fertiges PDF liegt jetzt auf https://github.com/thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler/tree/gh-pages.

**Comment by AKielhorn** [comment]
Das Buch lässt sich jetzt mit TeX-Live 2018 und 2019 bauen.
Damit sollte die CI jetzt durchlaufen.
