### ISSUE TITLE
Präsentationen mit beamer

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#13]
Hier kann man dieselbe Frage stellen: Gehört das Thema eigentlich in das Skript, oder ist es zu allgemein?

Ich denke, dass die Möglichkeit, sehr EINFACH sehr GUTE Präsentationen zu erstellen, ein Mehrwert ist, der manchen Geisteswissenschaftler überzeugen könnte.

Ich fühle mich aber ehrlich gesagt nicht besonders berufen, den Abschnitt auch zu verfassen.

**Comment by sieversMartin** [comment]
Ich denke, man sollte schon (grundlegend) beschreiben, wie man in LaTeX verfasste Gedanken von der Standardpublikationsform "Buch/A4" in eine Präsentation überführt.

**Comment by LukasCBossert** [comment]
Ich denke auch, dass das Thema `beamer` erläutert werden soll, wenngleich man nicht in Gänze die ganzen Features zeigen kann. Aber zumindest sollte man dann in der Lage sein, eine (einfache) Präsentation zu erstellen, sodass man für alle weiteren Fragen die entsprechende Fachliteratur (H.V. ›Präsentationen‹ etc) hinzuziehen kann.

**Comment by thomas-hilarius-meyer** [comment]
Gab es da nicht mal einen ziemlich aktuellen DTK-Artikel?
Ich gehe mal auf die Suche...

**Comment by AKielhorn** [comment]
Es gab auf der Tagung in Heidelberg einen Vortrag und in der DTK 2/2014 einen Artikel dazu.
Das Beispieldokument könnte man übernehmen (mit neuem Titelbild), genauso wie den Artikel. Dazu müsste nur die Struktur von DTK auf lfgw angepasst werden. (Das sind ca. 15 Seiten im DTK Layout)

**Comment by UweZiegenhagen** [comment]
Ich könnte mit wenig Aufwand ein passendes Kapitel beisteuern.
