### ISSUE TITLE
Erstellung eines Katalogs

### ISSUE THREAD

**Issue by LukasCBossert** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#15]
Wie in DTK 3/2016 erläutert, finde ich es hilfreich, wenn man eine Anleitung gibt, wie man auf effiziente Weise einen ›Katalog‹ erstellen kann. 

Dafür könnte man den DTK-Artikel (ohne die Python/TeX-Lösung mit Rückverweis) entsprechend übernehmen. 

Ein Feature, das für alle möglichen Sachen verwendet und modifiziert werden kann, sodass eine (große) Materialsammlung nach gleichen Kriterien geordnet und einheitlich ausgegeben werden kann.

**Comment by thomas-hilarius-meyer** [comment]
Auch diesen issue schließe ich, wenn's recht ist.
