### ISSUE TITLE
Struktur des Skripts (Fachspezifisches Kapitel)

### ISSUE THREAD

**Issue by LukasCBossert** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#16]
Um fachspezifische Lösungen anzubieten, könnte man im Skript am Ende ein Kapitel schreiben, dass auf einzelne geisteswissenschaftliche Fächer eingeht und für diese Fächer auf die Pakete im Skript verweist.

Bspw für die Fächer:
- Philosophie
- Altphilologie
- Archäologie
- Geschichte
- Kunstgeschichte
...

**Comment by thomas-hilarius-meyer** [comment]
Das ist eine sehr philosophische Frage.

Ehrlich gesagt war es mein erster Ansatz (vor ein paar Monaten, als ich angefangen habe, diese Idee zu bebrüten), das ganze Skript so aufzubauen:
Kap. 1 - Latex für Theologen (Hebräisch, griechisch,...)
Kap 2. - LateX für Germanisten (Krit Apparate) usw. usw.

Das Problem war, dass die meisten Geisteswissenschaftler doch dieselben Sachen brauchen und es deshalb haufenweise Wiederholungen oder Verweise gäbe. 

MEine Lösung war dann das "allgemeine Register" mit den ganzen Fachbegriffen aus den verschiedenen Disziplinen, die dem Theologen und Historiker, der ein -> Bibelstellenregister braucht, weiterhelfen soll.

Aber das ist nicht das letzte, in Stein gemeißelte Wort.

**Comment by LukasCBossert** [comment]
genau, weil ich auch denke, dass dass es dopplungen gibt, sollte der erste Teil des Skripts die Pakete/Makros/Code behandeln, und dann im zweiten Teil auf die Fachspezifischen Sachen eingehen (also so wie du es zuerst gedacht hast). Dann hat man, so denke ich, zwar ggf. etwas gedoppelt (nicht inhaltlich, sondern in den Verweisen), aber eine sehr gute Verzahnung von Fachspezifischen und Code.

**Comment by thomas-hilarius-meyer** [comment]
Hmm, jaa, das ist schon überzeugend.

Vielleicht kannst Du mal eine Kurzfassung deines Kapitels / der Kapitelfolge (nur die Stichworte) kreieren und an die entsprechende Stelle tun?

Ich denke doch, das aller-aller-meiste wird am besten im "allgemeinen Teil" aufgehoben sein...

**Comment by thomas-hilarius-meyer** [comment]
Hmmm, damit sind wir noch nicht fertig, bei aller Aufräumerei...

Wie ist denn Eure Meinung zu der Frage?

Ehrlich gesagt glaube ich, dass wir uns verheben, wenn wir jetzt noch fachspezifische Kapitel erstellen wollen. Ich denke, unsere lieben Leser wissen selbst am besten, was sie brauchen.
