### ISSUE TITLE
Erläuterung der Hilfeseiten (Internet, Fachbücher)

### ISSUE THREAD

**Issue by LukasCBossert** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#17]
Ein Kapitel zu weiterführenden (Internet)-Seiten; wo bekomm ich welche Hilfen, Vorlagen?

- http://tex.stackexchange.com
- https://ltxref.org (im stetigen Auf- und Ausbau)

# Blogs
- https://texandfriends.wordpress.com

# Templates
- http://www.latextemplates.com
-  http://pgfplots.sourceforge.net/gallery.html
- http://texample.net

# Hilfsprogramme
- http://latexdraw.sourceforge.net
- http://truben.no/table/

**Comment by thomas-hilarius-meyer** [comment]
Ich habe etwas über Bücher schon drin vorgsehen (im Anhang); hänge doch dort eine Section an "Wie finde ich Unterstützung im Netz" oder so...

Und hinterlass bitte eine Spur im REAME ...

**Comment by thomas-hilarius-meyer** [comment]
Das würde dann an die Stelle  13.4 gehören.
Ich kopiere es 'mal dorthin...

**Comment by thomas-hilarius-meyer** [comment]
Ich denke, auch hier können wir den Hörer auflegen...
