### ISSUE TITLE
Bibliographiestil im Skript

### ISSUE THREAD

**Issue by LukasCBossert** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#18]
Aktuell wird `\usepackage[style=verbose-inote,pageref=true,backend=biber]{biblatex}` geladen. Gibt es einen bestimmten Grund für diesen Stil?

`style=historische-zeitschrift` ist ja leider nicht mit der aktuellen `biblatex/biber`-Version kompatibel.

Welche geisteswissenschaftliche Stile (die up-to-date sind) kennt/verwendet ihr?

**Comment by thomas-hilarius-meyer** [comment]
Der Stil (historische-zeitschrift) war halt so schön und für Historiker so vertraut.
Aber er geht ja nicht mehr. 
Buuuhuuuu!!!!!

Der jetzt eingestellt Stil kam mir so ähnlich vor, aber natürlich können wir ändern.

Die Frage wäre halt, wie kompliziert es ist, einen Stil wie für die HZ so anzupassen, dass er wieder läuft. Aber davon habe ich wirklich keine Ahnung.

Deshalb ja das Skript: Der begeistertste Leser werde ich selber sein...

**Comment by baem2** [comment]
Soweit ich das sehe, hat der Ersteller von hist-zs zumindest im Moment keine Zeit, das auf den Stand zu bringen.

Ich denke, wir sollten im Rahmen des Skriptes auf ein paar Stile und deren Optionen eingehen, aber nicht erklären, wie man einen eigenen Stil erstellt bzw. einen existierenden tiefergehend anpaßt, denn das wird schnell einigermaßen komplex. Problematisch ist, daß die verschiedenen geisteswiss. sehr unterschiedliche Zitierstile pflegen und ich keine Ahnung hab, ob das mit den vorhandenen Stilen einigermaßen abgedeckt wird ...

Welchen Stil wir im Skript verwenden, ist mir wurscht. Wie wär's mit biblatex-archaeologie -- der soll gut sein, hab ich gehört ;)

**Comment by LukasCBossert** [comment]
ja, leider sind  der HZ-Stil und die anderen `dw-Stile` nicht mit dem aktuellen `biblatex` kompatibel.
Wie Philipp erwähnt könnte man den stil `archaeology` nehmen (www.biblatex-archaelogie.de), der zwar primär den Richtlinien des deutschen archäologischen instituts folgt, aber durch sehr viele Optionen dem eigenen Wunschaussehen anpassbar ist; zudem kann man antike autoren zitieren.

**Comment by domwass** [comment]
Ich grätsche mal von der Seite hier rein (c: Wenn sich Leute finden, die mir bei der Aktualisierung meiner dw-Stile und von historische-zeitschrift behilflich sein können, ist der Aufwand nicht allzu groß, denke ich. Herbert Voss hat mir freundlicherweise einige Hinweise zur Anpassung geschickt, die ich einbauen könnte. Ich habe nur keine Zeit, daraus ein CTAN-Paket zu schnüren und hochzuladen. Da könnte ich Hilfe gebrauchen. Beide Pakete hoste ich auf sf.net.

**Comment by sieversMartin** [comment]
Ich kann gerne helfen, insbesondere auch beim CTAN-Upload. Geht es in erster Linie um die geänderter Namensverarbeitung?

**Comment by domwass** [comment]
Danke, Martin. Ja, es geht im Wesentlichen um `\DeclareNameFormat`. Ich habe bisher selbst noch keine Zeit gehabt, mir das im einzelnen anzusehen, aber ich denke, dass die Anpassung von `\DeclareNameFormat` schon ausreichen würde, um die Kompatibilität mit dem aktuellen biblatex wiederherzustellen.

**Comment by sieversMartin** [comment]
Ich musste selbst damals auch einen Stil anpassen. Ich denke, es ist letztlich eine Fleißaufgabe. Man muss eben alle Stellen identifizieren und dann nach Schema umbauen.

**Comment by LukasCBossert** [comment]
_eigentlich_ sollte es _nur_ eine copy/paste-Arbeit sein?!

**Comment by sieversMartin** [comment]
Letztlich ja. Dominik hat mir die überarbeitete Fassung geschickt, die man aus meiner Sicht als v1.2 auf CTAN hochladen könnte. Voraussetzung ist dann biblatex >v3.3

**Comment by domwass** [comment]
Ich werde mal versuchen, mir ein bisschen Zeit rauszuschneiden, um zumindest die Kompatibilität von biblatex-dw mit dem aktuellen biblatex wiederherzustellen. Das ist ja ein flexibleres Paket, mit dem man das Aussehen der Bibliographien recht einfach anpassen kann (hoffe ich). Und da es in den Geschichtswissenschaften (und allgemein in den Geisteswissenschaften) so viele verschiedene Zitierstile gibt, ist es ja eigentlich schön, wenn man nicht für jedes Dokument einen neuen biblatex-Stil laden muss, sondern mit ein paar Einstellungen das Aussehen anpassen kann. (Das jedenfalls war die Idee hinter biblatex-dw.) Und es wäre natürlich schön, wenn das in lfgw auch an Beispielen gezeigt werden kann – und biblatex-dw generell wieder einsetzbar ist.

**Comment by LukasCBossert** [comment]
das wäre super, denn biblatex-dw ist ja schon weit verbreitet und für viele eine Hilfe. Ich sammle hier https://github.com/thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler/issues/14 mal die zu erläuternde Stile

**Comment by domwass** [comment]
> biblatex-dw ist ja schon weit verbreitet
Dazu habe ich, ehrlich gesagt, gar keine Informationen. Ich weiß, dass der Stil genutzt wird, da es gelegentlich Bug-Reports gibt. Aber wie weit er tatsächlich verbreitet ist, weiß ich gar nicht. [Würde mich aber natürlich interessieren.]

**Comment by thomas-hilarius-meyer** [comment]
Wenn Ihr den Historische-Zeitschrift-Stil anpassen könnte, wäre mir der eigentlich am liebsten für lfgw.
Aber das ist nur subjektiv, das muss nicht sein...

**Comment by sieversMartin** [comment]
Ich werde Morgen die korrigierte Version v1.2 auf CTAN hochladen.

**Comment by domwass** [comment]
@sieversMartin Danke für die Hilfe.
Zu biblatex-dw: Ich habe es (dank der großartigen Vorarbeit von Herbert Voss) geschafft, die Kompatibilität zum aktuellen biblatex 3.6 herzustellen. Jedenfalls waren meine Tests erfolgreich. Bevor ich nun eine neue Version auf CTAN hochlade, möchte ich Euch bitten, das Ganze einmal zu testen und mir Rückmeldungen zu geben. Da die hier an der falschen Stelle sind, verweise ich für etwaige Bug-Reports auf das [sourceforge-Repository](https://sourceforge.net/p/biblatex-dw/tickets/). Den aktuellen Code von biblatex-dw [gibt es hier](https://sourceforge.net/p/biblatex-dw/code/ci/master/tree/biblatex-dw-code/). Für positive Rückmeldungen könnt Ihr mir eine kurze Mail an biblatex@dominik-wassenhoven.de schicken.

**Comment by baem2** [comment]
@domwass, ich bin noch mit altem biblatex unterwegs, deswegen ist das Testen ein bißchen kompliziert. Sollte sich aber sonst niemand finden, sag Bescheid, dann werde ich mir eine Test-Umgebung zusammenbasteln.

**Comment by domwass** [comment]
@baem2, wenn Du TeX Live hast, kannst Du das neue ganz einfach installieren, ohne das alte zu entfernen. Im TeX Live Utility kannst Du dann jede installierte Version auswählen (Configure > Change Default TeX Live Version), also 2015 für altes biblatex, 2016 für neues. So hab ich es gestern beim Testen gemacht.

**Comment by baem2** [comment]
Ja, leider habe ich TeXlive über die debian stable-Pakete und bin daher nicht so flexibel ... :(

(Und ja, es hat seinen Sinn, daß ich TeXlive/debian stable verwende: So ist sichergestellt, daß alle im Projekt die gleichen Paket-Versionen haben und sich am Aussehen des Projektes *nichts* ändert ...)

**Comment by thomas-hilarius-meyer** [comment]
Ich selber habe geschrieben, dass es ein großer Vorteil von overleaf und
co. ist, dass man sich nicht um die TeX-Installation kümmern muss.

arktisvogel konnte unser Skript zuerst nicht kompilieren, weil die Pakete
nicht installiert waren.

Vielleicht sollten wir lfgw einen Abschnitt über TeX-Live spendieren? Ganz
kurz, max. 2 Seiten?

Am 3. Dezember 2016 um 08:50 schrieb Dominik Waßenhoven <
notifications@github.com>:

**Comment by sieversMartin** [comment]
> Vielleicht sollten wir lfgw einen Abschnitt über TeX-Live spendieren? Ganz kurz, max. 2 Seiten? 

Es sollte auf jeden Fall etwas zur Installation geben (Fallstricke inkl.)

**Comment by LukasCBossert** [comment]
Ja, finde ich gut. Erklärung was Tex live miktex etc ist und wie man ggf. Update von Paketen etc macht

Von meinem iPhone gesendet

**Comment by baem2** [comment]
Ich hab dafür #28 aufgemacht, um diese issue hier etwas zu entlasten ...

**Comment by sieversMartin** [comment]
> Ich werde Morgen die korrigierte Version v1.2 auf CTAN hochladen.

Zur Info. Die Version kann ab sofort per tlmgr für TeX Live aktualisiert werden.

**Comment by thomas-hilarius-meyer** [comment]
Akte geschlossen.
