### ISSUE TITLE
Typografische Probleme?

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#19]
Warum verrutschen  die Texblöcke im Bereich des Parallelsatzes auf Seite 50?
Seht Ihr, was ich meine?
Oder habe ich ein Viewer-Problem?

**Comment by baem2** [comment]
Also bei mir erscheint im rechten Textblock in Z. 3 eine Leerzeile, die da nicht sein sollte. Danach ist alles eine Zeile nach unten verrutscht. Das Problem trat bei mir bei Parallel öfters auf und ich hab es manchmal wegbekommen.

Das war aber einer der Gründe, warum ich auch für solchen Kleinkram mittlerweile reledpar verwende ...

**Comment by thomas-hilarius-meyer** [comment]
Issue closed.
