### ISSUE TITLE
Bibelstellenregister mit bibleref-german

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#20]
Für ein Projekt wollte ich ein Register der zitierten Bibelstellen erstellen. Dieser Index soll nicht alphabetisch sortiert werden, sondern natürlich in der Reihenfolge der biblischen Bücher: Gen, Ex, Lev usw....

Deshalb habe ich schon vor ein paar Monaten die entsprechenden Sortierschlüssel in das Paket bibleref-german eingebaut.

Der ursprüngliche Autor des Paktetes, Dr. Dominik Waßenhoven, hat zugestimmt, dass wir das Paket auf github stellen. VIELEN DANK DAFÜR!!!

Ich habe also als ersten Schritt 'mal den aktuellen Stand, so wie er auf CTAN heruntergeladen werden kann, als Projekt bibleref-german eingerichtet.

So wie ich dazu komme, werde ich die von mir vorgenommenen Änderungen committen.

Das überarbeitete Paket ist nicht wirklich fertig, sondern in dem Zustand, dass es das machte, was ich von ihm wollte.
Ich bin im Moment etwas knapp mit der Zeit und würde gerne zuerst das bibleref-Paket fertigstellen, damit ich dann in lfgw beim Punkt Bibelstellenregister bereits auf den neuen Stand eingehen kann.
Außerdem wollte ich einen DTK-Artikel zum Umgang mit Bibelstellen schreiben, den ich dann zur Grundlage des Abschnitts in lfgw machen wollte. (Der Artikel ist ziemlich fertig.)

Wer Lust hat, an dem Paket biblref-german mitzubosseln ist also auch hier herzlich eingeladen!

**Comment by baem2** [comment]
Was genau ist denn zu tun?

**Comment by thomas-hilarius-meyer** [comment]
Weitere Diskussion im eigegenen Repository,
issue geschlossen...
