### ISSUE TITLE
Frage des Endergebnisses

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#21]
Ich habe bemerkt, dass Ihr die PDF-Datei wesentlich bequemer zu navigieren gemacht habt...

Aber das führt mich zu der Frage, wie wir uns das Endprodukt unserer Arbeit vorstellen.
Ich muss gestehen, dass mir ein gedrucktes Buch tatsächlich am liebsten wäre. Das ist so ein sinnliches, greifbares Ergebnis...

Was denkt Ihr, wie stehen die Chancen auf eine Publikation in der Dante-Reihe. Die Titelseite legt das ja im Moment nahe.

Apropos Titelseite: Die Verfasserangabe stimmt so längst nicht mehr...

**Comment by UweZiegenhagen** [comment]
Ich denke, die Chance auf ein Buch ist ziemlich hoch.

Uwe

--
www.uweziegenhagen.de

**Comment by baem2** [comment]
Ein Buch ist immer schön ...

**Comment by baem2** [comment]
... wenn es ein Buch wird, müssen wir bei der Verwendung von Abbildungen vorsichtig sein (ich meine nicht wegen des Platzes, sondern der Rechtelage). Auch sollte man nicht zu großzügig aus Paketdokumentationen "zitieren".

**Comment by LukasCBossert** [comment]
ich würde auch das Buch anvisieren!

Bzgl. Rechtelage bei Abbildungen: solange die Autoren schon 70 Jahre tot sind, haben wir kein Problem. Die Abbildungen, die ich gesehen habe, sind 2D-Repro, die somit keinem Urheberrecht unterliegen und wir damit benutzen können.

Paketdokumentationen sind (an sich meistens!?) ohnehin in der Lizenz freizügig, sodass man da durchaus "zitieren" kann (zumal wir dann ja sicherlich die Quelle angeben).

**Comment by arktisvogel** [comment]
TeX war nie entworfen um Internetfähigen Hypertext-Dokumente zu erstellen. Da wo Features in einem PDF-Dokument mühelos einzubinden sind, kann ich akzeptieren. Aber, lassen wir uns den Ziel setzen die Welt zu zeigen, dass TeX für den Buchsatz kaum zu schlagen ist.

**Comment by sieversMartin** [comment]
Na ja, vieles, was heute mit TeX geht, war so ursprünglich nicht vorgesehen ...

Grundsätzlich stimme ich aber zu, dass das Ziel dieses Projekts eine gedruckte Publikation sein sollte.

**Comment by sieversMartin** [comment]
> Was denkt Ihr, wie stehen die Chancen auf eine Publikation in der Dante-Reihe. Die Titelseite legt das ja im Moment nahe.

Versprechen kann ich nichts, doch hat DANTE e.V. gute gewachsene Kontakte zu Lehmanns und ist an weiteren Bücher der Reihe sehr interessiert.

**Comment by baem2** [comment]
War schon was von Lehmanns zu hören?

**Comment by thomas-hilarius-meyer** [comment]
Rama dama...

**Comment by baem2** [comment]
Ich mach hier mal wieder auf, mit dieser Frage: Was eigentlich sagt ein Verlag dazu, wenn das Buch als pdf (nämlich hier) komplett verfügbar ist?

**Comment by sieversMartin** [comment]
Derzeit ist es ja noch kein fertiges Buch ;-)

Ansonsten hast du natürlich recht und der Punkt müsste geklärt werden. Kann ich bei der Frühjahrstagung mal versuchen.

KOMA-Script und Mathematiksatz gibt es auch als kostenfreies PDF, allerdings nicht so schön gesetzt wie das Buch. Das könnte eine Variante sein.
