### ISSUE TITLE
Eigene LaTeX-"Erfindungen" dokumentieren

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#22]
Ich denke, wir sollten uns auf eine Konvention einigen, wie wir LaTeX-Code im Skript wiedergeben und die Ergebnisse dieses Codes präsentieren.

Das von mir faut de mieux verwendete Paket LTXemample hat ja Probleme. Eine Alternative wurde vorgeschlagen...

Vielleicht wäre es praktisch, wenn wir zuerst DIESES Kapitel im lfgw schreiben würden, dann können wir uns bei der weiteren Arbeit an unsere eigene Beschreibung halten.

Es wurde auch moniert, der Begriff "LaTeX-Erfindungen" sei nicht passend. Wie so vieles an meinem Skript war das einfach aus der Hüfte geschossen. Ich denke schon, dass - vielleicht sogar: gerade! - Geisteswissenschaftler LaTeX-Code dokumentieren müssen. Deshalb gehört das Thema m.E. unbedingt in lfgw. Meine Titelformulieren sollte ein wenig selbstironisch klingen, aber man kann das bestimmt besser formulieren.

Ich würde den Abschnitt gerne abtreten, weil ich in den kommenden Wochen (bis zu den Weihnachtsferien) wohl nicht so viel Zeit hineistecken kann und von der LaTeX-Dokuemtation - wie von so vielem - nicht so viel verstehe.

Wer möchte den Abschnitt übernehmen?
Wer kann möglichst bald einen Entwurf liefern, denn wair dann im Rest des Skripts umsetzen können?

**Comment by UweZiegenhagen** [comment]
Hast Du mal gesehen, wie ich es im "exam" Kapitel gemacht habe?

Uwe

--
www.uweziegenhagen.de

**Comment by baem2** [comment]
LaTeX-Erfindungen dokumentieren: Ich weiß nicht, ob ich das hier richtig verstanden habe. Für meine Zwecke (auch in Projekten mit mehreren Mitarbeitern) hat immer gereicht, bei eigenen Erfindungen über das newcommand 1-2 auskommentierte Zeilen zur Erklärung zu schreiben. Wie das geht (und warum das sinnvoll ist), sollten wir erklären.

Ich glaube aber nicht, daß die gw. nun unter die Paket-Entwickler gehen, und wenn sie das tun, ist dieses Script nicht der Ort, um Ihnen zu erklären, wie sie eine richtige Dokumentation anlegen?

**Comment by thomas-hilarius-meyer** [comment]
Ich weiß nicht, ich glaube, ich bin anderer Meinung.

Erstens: Natürlich gibt es Geisteswissenschaftler, die Pakete entwickeln. Wo kommen die ganzen Pakete denn her, die wir hier kommentieren ;-)

Zweitens und ernsthafter: Wenn LaTeX geboostet werden soll, dann wird das stark darüber laufen, dass Anwender wie "du" und "ich" ihr Tun dokumentieren.

Drittens und sehr philosophisch: Ich finde das Dokumentieren von LaTeX-Code im Prinzip eine philologische Betätigung: Hier wie dort geht es darum einen Objekttext durch einen Beschreibungstext einzurahmen, zu kommentieren etc. Kurz: Textwissenschaft halt. Nur liegt die Textquelle nicht in Keilschrift vor, sondern in TeX. Ähnlich kryptisch... ;-)

Ich finde, ca. ein-zwei Seiten über LTXexample bzw. seinen zeitgemäßen Nachfolger wären schon cool. Die fressen doch kein Heu...

**Comment by UweZiegenhagen** [comment]
Wer diese Seiten schreibt, hat recht.  :-)

Von meinem iPhone gesendet

**Comment by LukasCBossert** [comment]
wurde hier nicht auch schon tcolorbox diskutiert? 
Damit kann man `listings` ja integrieren und hat eine ›doppelte‹ Anzeige von Code und ›Ausgabe‹?

```
\usepackage[%
  skins,%
  listings,%
  breakable,%
]{tcolorbox}

\newtcblisting{example}{%
before skip=\baselineskip,
boxrule=0pt,
bottomrule=2pt,
toprule=2pt,
colframe=black,
colback=black!10,
coltitle=grey!10,%  coltitle=codeblue,
bicolor,
sharp corners,
fontupper=\small\ttfamily,
colbacklower=blue!10,
fonttitle=\sffamily\bfseries,breakable,
%  sidebyside,
listing and text,
}
```

im Text:

```
\begin{example}
This is a footnote\footnote{some footnote text}
\end{example}
```

**Comment by baem2** [comment]
> wurde hier nicht auch schon tcolorbox diskutiert?

Jo, hier #3

**Comment by LukasCBossert** [comment]
Ah - danke, dann machen wir es so wie auch @sieversMartin vorgeschlagen hat und wir steigen auf `tcolorbox` um? Da kann man dann immer noch die eigenen Stile (relativ leicht) erstellen und anpassen (nur code, code und Ausdruck, nur Ausdruck etc).

**Comment by baem2** [comment]
Ja, das klingt doch gut! Ich assigne mal gleich die andere issue an Dich ;)

**Comment by thomas-hilarius-meyer** [comment]
Fall erledigt...
