### ISSUE TITLE
LaTeX Crash-Kurs für Plain-TeX Wizards

### ISSUE THREAD

**Issue by arktisvogel** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#24]
Ich setze gern mit Plain TeX. Ich kann mich manchmal einmogeln, und halbwegs vernünftige Dokumente mit LaTeX erfassen, aber `LaTeX für Geisteswissenschafter` hat so viele Abhängigkeiten, dass ich es nicht einmal interpretieren kann an meinem System (Debian Linux ``Jessie''). Da ich es ernsthaft vorhabe bei diesem Projekt mitzumachen, brauche ich von Euch manche Hilfe, die für einen LaTeX Wizard mehr als peinlich wäre.

Manches fällt unter den Kategorie: ``Was sagt der Chef über wie wir es einheitlich formatieren sollen?'' Anderes hat einfach damit zu tun, dass echte LaTeX-Users wissen was normal ist.

Eine konkrete anliegen: wenn ich in einem LaTeX-Dokument beschreiben möchte, wie man Tastatur-Eingabe machen soll, gibt es garantiert einen Paket zu. Möglicherweise gibt es sowas nutzliches in einen von denen Pakete die schon ge-usepackaget sind.

In welchem Paket finde ich den \minisec Makro? (Ich werde meinem Hausaufgabe fleissig machen.)

**Comment by UweZiegenhagen** [comment]
Zu Tastatur-Eingaben schau dir mal http://ctan.org/pkg/keystroke an

Uwe

--
www.uweziegenhagen.de

**Comment by thomas-hilarius-meyer** [comment]
minisec gehört zu den KOMA-Script-Klassen und ist m.E. sehr praktisch für solche "kleinen" Überschriften, die nicht ins Inhaltsverzeichnis kommen müssen.

**Comment by arktisvogel** [comment]
Gut, ich mach' mich schlau in der Sache ``keystroke'' und ``KOMA-Script''.
