### ISSUE TITLE
Abschnitt zu "komplexe Bildunterschriften mit Excel/OpenOffice"

### ISSUE THREAD

**Issue by UweZiegenhagen** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#25]
Hi zusammen,

ich habe gute Erfahrungen damit gemacht, mehrzeilige Bildunterschriften mit Excel vorzubereiten und dann mittels Excel-Funktionen in ein \caption{} Konstrukt zu verwandeln. Das würde ich gern beschreiben, aber wo füge ich es am besten ein?

Uwe

**Comment by thomas-hilarius-meyer** [comment]
Lieber Uwe,

natürlich könnte man es zu den Bildern und dem caption-Paket stellen (im
Kapitel "Texte schreiben").

Aber wie wäre eine andere Idee: Wir machen ein eigenes Kapitel, wo wir
verschiedene Möglichkeiten aufzeigen, LaTeX mit anderer Software
zusammenarbeiten zu lassen. Das würde dann an verschiedenen Beispielen
exemplarisch gezeigt:

* Der Katalogerstellung m.H. von Python
* Deinem Excel-Beispiel für Bildunterschriften
* evtl. noch andere, spezielle Beispiele für XYZ m.H. von Perl, Lua, ...

Was denkt Ihr?

Am 3. Dezember 2016 um 07:25 schrieb Uwe Ziegenhagen <
notifications@github.com>:

**Comment by UweZiegenhagen** [comment]
Find ich gut. Ich lege die entsprechende Kapitel-Datei mal am Wochenende ein und füge das Grundgerüst meiner Section ein.

Uwe
