### ISSUE TITLE
EMACS-Spezifika

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#26]
V.a. @ arktisvogel:
Ich meine, wir sollten Bedienungshinweise zu einzelnen Editoren, auch wenn es sich um den höchst ehrwürdigen EMACS handelt, nicht einfach so in das LaTeX-Skript einstreuen, sondern in einem eigenen Kapitel / Abschnitt zusammenfassen. EMACS ist bestimmt toll, aber er ist nicht der Standard-Editor für TeX. Aus gutem Grund gibt es so etwas wie einen Standard-Editor für TeX nicht.

Außerdem wäre es m.E. besser, wenn längere eingefügte Textpassagen mit einer Autorangabe versehen wären (über deren Vereinheitlichung wir noch sprechen sollten), die auch in der PDF-Datei sichtbar ist.

**Comment by UweZiegenhagen** [comment]
Finde ich gut. Vielleicht in einem Kapitel "Überblick über verschiedene Editoren"

**Comment by sieversMartin** [comment]
Aus meiner Sicht sollte man einen Editor global empfehlen (z.B. TeXstudio) und dessen Möglichkeiten an verschiedenen Stellen aufgreifen (evtl. speziell gekennzeichnet)

**Comment by sieversMartin** [comment]
> Jeder von uns kann ja ein Makro/eine Umgebung mit seinem Namen definieren, die man denn entsprechend layouten kann (Farbe, Namensnennung o.ä.)

**Comment by baem2** [comment]
Ich würde Martin zustimmen, daß wir einen Editor ausführlicher vorstellen und dann durchgehend in den Beispielen verwenden. Sonst muß der Leser sich im Zweifelsfall für jedes Kapitel einen anderen Editor besorgen. Es spricht natürlich nichts dagegen, einige weitere Editoren vorzustellen.

TeXstudio bietet sich als "globaler Editor" an, weil es auf allen gängigen Plattformen läuft ...

**Comment by sieversMartin** [comment]
> TeXstudio bietet sich als "globaler Editor" an, weil es auf allen gängigen Plattformen läuft ...

Und für Anfänger wie Fortgeschrittene aus meiner Sicht sehr gut geeignet ist und einige nette "Gimmicks" hat.

**Comment by thomas-hilarius-meyer** [comment]
Wobei anzumerken bleibt, dass die allerallerallermeisten Abschnitte von
lfgw mit der Editorfrage garnix zu tun haben. Thats not a bug, that's a
feature.

Am 3. Dezember 2016 um 08:29 schrieb Martin Sievers <
notifications@github.com>:

**Comment by arktisvogel** [comment]
Da ich Linux und Windows bedienen kann, möchte ich auch einen Hinweis auf Betriebssystem-Paradigmen bringen. Ich kann auf einem Linux-System und einem Windows-System Texte in Emacs erfassen. Aber die Paradigmen für meinem **Workflow** gestalten sich notwendigerweise unterschiedlich.

Auf Linux speichere ich gern ein Handfull Dateien in einem Verzeichnis: ``/home/arktisvogel/Guru-Knowledge/TeX/pdfTeX/LuaTeX/LuaLaTeX/ngerman/``. Es dient mir um einen Übersicht von Themenbereiche zu behalten. Aber unter Windows, manche Anwendungen (insbesonders Editoren) können mir nur die linke Ende dieser langen Pfad anzeigen. In Windows tendiere ich einen ganz andere Arbeitsweise zu suchen.
Mein Hauptpunkt ist: lassen wir uns nicht in einem Diskussion kommen welcher Editor im Mittelpunkt zu stellen ist, da es ganz stark mit **Workflow**-Paradigmen zu tun hat.

**Comment by baem2** [comment]
Falls es hier keinen Widerspruch mehr gibt, dann fasse ich das mal so zusammen: Die meisten Kapitel sollten ohne direkten Bezug auf einen Editor klarkommen. Wenn Beispiele einen Editor direkt einbeziehen, dann am besten TeXstudio.

Gut?

**Comment by LukasCBossert** [comment]
Da stimme ich dir zu.

**Comment by baem2** [comment]
Erledigt.
