### ISSUE TITLE
Automatische Erzeugung der PDF-Datei

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#27]
Gibt es eine Möglichkeit, git / github dazu zu bringen, die PDF-Datei automatisch zu erzeugen, sobald ein neuer Commit ausgeführt wird?

**Comment by UweZiegenhagen** [comment]
Theoretisch ja. Über automatisierte Build Tools (Jenkins?) sollte das machbar sein. Hab ich aber noch nie ausprobiert. Wäre mal eine Gelegenheit...

**Comment by sieversMartin** [comment]
Sollte mittlerweile über Hooks etc. klappen. Ich kann gerne mal schauen.

**Comment by UweZiegenhagen** [comment]
Hooks wären auch meine Idee. Aber da github vermutlich kein TeX hat, dürfte es doch nur auf einer lokalen Maschine klappen.

**Comment by UweZiegenhagen** [comment]
Ich habe mir gestern mal Jenkins angeschaut, damit geht das. Ich werde dazu mal einen Blogartikel und eventuell sogar einen DTK Artikel verfassen.
