### ISSUE TITLE
TeX-Distribution(en) vorstellen

### ISSUE THREAD

**Issue by baem2** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#28]
Wir brauchen einen Freiwilligen, der die TeX-Distributionen vorstellt ...

Siehe die Diskussuion hier: https://github.com/thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler/issues/18#issuecomment-264627027

**Comment by sieversMartin** [comment]
Das könnte ich machen.

**Comment by baem2** [comment]
first come, first serve ...

**Comment by thomas-hilarius-meyer** [comment]
Auch hier ist eigentlich alles gesagt, oder?
