### ISSUE TITLE
Guidelines

### ISSUE THREAD

**Issue by sieversMartin** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#29]
Ich habe eine Datei GUIDELINES ergänzt, um festzuhalten, welche Dinge wir als Autoren beim Verfassen der Texte beachten sollen.

Die Liste darf gerne diskutiert bzw. ergänzt werden.

Ich habe z.B. Makros für Inline-Codeschnipsel ergänzt, die der `ltxdoc`-Klasse entsprechen:
`\cs{MAKRONAME\marg{Argument}}` und das ganze um Varianten `\marg*` bzw. `\oarg*` ergänzt, die ihr Argument nicht in spitze Klammern setzen, also für konkrete Argumente sinnvoll sind.

**Comment by arktisvogel** [comment]
Ich wurde einen einheitlichen typografische Norm begrüssen, wie wir im Skript eine Zeichenkette als __Anwendung__ (z.B. nano), oder als __LaTeX-Paket__ (z.B. toc-etc) kennzeichnen können. Besonders neuen Benutzer könnten missverstehen dass, solche Begriffe eine Art *Insider-Jargon* sind.

**Comment by baem2** [comment]
Solche Sachen können wir aus der DTK übernehmen (zB \Program), soweit sie nicht ohnehin schon definiert sind (zB \paket):

http://projekte.dante.de/DTK/Eigennamen

**Comment by sieversMartin** [comment]
Eine gute Idee. Ich werde das so einbauen.

Wichtiger als die typographische Festlegung ist derzeit aus meiner Sicht die Nutzung einheitlicher Makros, um später flexibel agieren zu können.

**Comment by arktisvogel** [comment]
Dass mit `paket` und `Program` ist genau nach meinem Geschmack.

Ähnlich wie die Formatierungen, habe ich eine frage nach bestimmte Schreibweise die ich im Skript gesehen habe. Ich möchte wissen ob es Vorteile hat eine der Formatierungen über die anderen zu ziehen.

> intern auf \texttt{article} basiert, werden alle Fragen mittels \texttt{\textbackslash question} Befehl

im Vergleich zu:

> Kleine Tiere \lstinline/\usepackage{runic}/ mit dem \lstinline/\textfut{}/ Fussball.

**Comment by sieversMartin** [comment]
Direkte Formatierungsanweisungen wie `\texttt`, `\textbf` etc. zu nutzen, hat den großen Nachteil, dass man keinerlei semantische Information zu dem entsprechenden Element mehr hat (Stichwort "logisches Markup") und die Formatierung auch nicht mehr im Vorspann der Datei anpassen kann. Anpassungen im Text sind auch sehr schwierig, weil man eben nicht mehr zwischen einem Programmnamen, der in Typewriter gesetzt wurde und einem aus anderem Grund in Typewriter gesetzten Begriff unterscheiden kann.

`lstinline` ist da etwas besser, letztlich legt man sich damit aber auch schon sehr fest.

Daher bevorzuge ich Makros wie `\paket` oder `\cmd`, die nebenbei z.B. auch die automatische Erzeugung eines Registers ermöglichen.

**Comment by UweZiegenhagen** [comment]
Welche Befehle stehen denn schon zur Verfügung? `\paket{}` klappt, hab ich eben ausprobiert.

**Comment by baem2** [comment]
Alle aus der DTK sind nun da: e72c310b452c0843b149db140afd0cb11132c60e

**Comment by baem2** [comment]
Wenn es dazu morgen keinen Widerspruch gibt, trag ich TeXstudio als Referenz-Editor in die Guidelines ein, s. #26.

**Comment by thomas-hilarius-meyer** [comment]
Ich denke, aus Gründen der Übersichtlichkeit mache ich hier zu...
