### ISSUE TITLE
Problem in Listings: Umlaute mit LTXexample

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#3]
Ein Problemchen, das ich im ersten Ansatz nicht in den Griff bekommen habe, betrifft die Umlaute in den mit LTXexample dokumentierten Beispiellisten: Diese gehen verloren.

Wer weiß Hilfe?

**Comment by sieversMartin** [comment]
Das Problem ist wohl nicht so einfach in den Griff zu bekommen, denke ich. Ich schlage daher vor, dass wir auf tcolorbox umsteigen. Vgl. dazu auch https://tex.stackexchange.com/questions/252222/how-to-use-showexpl-with-tufte-handout

**Comment by LukasCBossert** [comment]
von https://github.com/thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler/issues/22#issuecomment-265695506 ausgehend: Sehr gut, ich werde entsprechende Umgebungen bauen und sie in der Wiki (https://github.com/thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler/wiki) dokumentieren. 
Vielleicht können wir alle die im Text verwendeten und zu verwendenden Makros dort eintragen, damit man bei Bedarf immer nachschauen kann.

**Comment by LukasCBossert** [comment]
Drei Möglichkeiten (siehe Wiki) sind eingebaut. dürfen natürlich gerne modifiziert werden (und müssen sie noch - wer also mehr Erfahrung mit `tcolorbox` hat, darf mir gerne helfen).

**Comment by thomas-hilarius-meyer** [comment]
Und auch dieser issue wird zur Geschichte...
