### ISSUE TITLE
\PrtScroll undefined

### ISSUE THREAD

**Issue by UweZiegenhagen** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#30]
Beim Übersetzen bekomme ich die Meldung, dass \PrtScroll  nicht definiert ist. Kann das jemand nachholen?

**Comment by arktisvogel** [comment]
In `keystroke.sty` ist es als `\PrtSc` definiert.

**Comment by thomas-hilarius-meyer** [comment]
Brauchen wir das wirklich? 
Habe ich doch richtig verstanden: Es geht um eine Sonderdarstellung für die (von mir noch  nie benutzte...) Taste "Drucken" (auf deutschen Tastaturen - Print Screen auf amerikanischen Modellen)?

Wenn ich schon die TASTE nie brauche, brauche ich dann ein TeX-Makro zu ihrer Darstellung?

Ich würde hier - glaube ich - zu Verzicht, Enthaltsamkeit und Bescheidenheit raten... ;-)

**Comment by baem2** [comment]
Hat sich das erledigt? Tritt das Problem noch irgendwo auf?

**Comment by UweZiegenhagen** [comment]
Nein, läuft jetzt problemlos durch.
