### ISSUE TITLE
Upsi! (GIT-Problem...)

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#31]
Hilfe! (DAU-Problem...)

Ich sage:  git pull

Und "es" antwortet mir:  "There is no tracking information for the current branch.
Please specify which branch you want to merge with."

Ich kontere:  git pull http://github... master

Und bekomme zurück: "error: Untracked working tree file ... would be overwritten by merge"

Hä?
Ich akzeptiere auch ein herzhaftes RTFM und gelobe, dass ich mir ein git-Buch bestellt habe...

**Comment by sieversMartin** [comment]
Ging es vorher denn genau so, also nur mit `git pull`? Neuer Rechner?

Schau dir mal die Antwort unter http://stackoverflow.com/questions/32056324/git-pull-there-is-no-tracking-information-for-the-current-branch an.

**Comment by thomas-hilarius-meyer** [comment]
Oja, ich habe ein bisschen Durcheinander mit verschiedenen Computern gemacht...
(Wer's wissen will: Das Skript habe ich ursprünglich auf meinem Netbook geschrieben, dann mit einem Stick auf den Desktop übertragen, von dort nach github gestellt, zwischenzeitlich auf dem Netbook git installiert und wollte jetzt die neue Version 'runterziehen und weiterbosseln...)

Es gibt git für Linux und Windows. Warum nicht für menschliche Hirne?
