### ISSUE TITLE
Tastendarstellung wirklich nötig?

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#32]
Ich beziehe mich auf die Seiten 33/34.

Meint ihr wirklich, dass die doch sehr massive Darstellung der Tasten wirklich nötig ist?

Wäre es nicht eleganter, einfach von der <ALT>-Taste zu sprechen, statt diese Grafiken einzufügen?
Und grundsätzlich: Wir verfassen eine Anleitung zu LaTeX, und nicht zu bestimmten Editoren. Sonst wird unser Verfahren m.E. uferlos...

**Comment by arktisvogel** [comment]
Ich habe soeben einen Version ohne grafischen Darstellungen ge-pusht.

**Comment by arktisvogel** [comment]
Ich wurde es in Ordnung finden, das Abschnitt über Emacs zu lassen, und das von `gedit` zu streichen. Ist dass in deinem Sinne?

**Comment by thomas-hilarius-meyer** [comment]
Ja, das wäre vielleicht ein guter Kompromiss zwischen dem Geben von konkreten Hilfen und der Programm-Unabhängigkeit einer allgemeinen LaTeX-Beschreibung.
Dass kann man ja bei EMACS auch "zum Beispiel" sagen und für andere Editoren auf deren Dokumentation verweisen.

**Comment by LukasCBossert** [comment]
Man kann ja auch die Tastendarstellung (was ich an sich eine gute Sache finde! [gerade das ist ja auch ein Pluspunkt von TeX]) von Libertine nehmen, dann hat man bzgl. Font alles aus einer Hand:
http://www.linuxlibertine.org/fileadmin/user_upload/PDF/Tastatur.pdf

**Comment by thomas-hilarius-meyer** [comment]
RIP Issue #32...
