### ISSUE TITLE
html-Datei

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#33]
Noch eine DAU-Frage:
Was macht die HTML-Datei hier?

Ich glaube git, ist ein größeres Thema, als Anfangs gedacht...

**Comment by sieversMartin** [comment]
Ich denke, da hat jemand über die GUI die .tex-Datei herunterladen wollen.

Ein Rechtsklick->Ziel speichern unter klappt da aber nicht ...

**Comment by sieversMartin** [comment]
`git rm ...` entfernt die Datei(en) aus dem Repository (und lokal).
`git rm --cached ...` löscht die Datei(en) nur aus dem Index/Repository. Lokale Kopien bleiben erhalten.

**Comment by sieversMartin** [comment]
Nochmal der Hinweis auf TortoiseGit als GUI. Da ist vieles leichter zu finden.

**Comment by baem2** [comment]
Ich assigne mal an @arktisvogel, der die Datei hochgeladen hat: die lfgw.tex.html können wir löschen, oder?

**Comment by arktisvogel** [comment]
@baem2 Die Datei kann gelöscht werden. Es wurde von mir mit einem überflüssigen `merge` wieder hochgeladen, wegen mein nicht ausreichende `git`-Kenntnisse.

**Comment by baem2** [comment]
Gut, danke für die Rückmeldung, hab ich gemacht.
