### ISSUE TITLE
Modifizierte Listen...

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#34]
... sind sehr cool.
Vielen Dank!

**Comment by thomas-hilarius-meyer** [comment]
.. Aber vielleicht magst Du dann auch noch den Hinweis auf S. 22 ergänzen?
(Gerade entdeckt... Der Paketname kam mir doch so bekannt vor...)

**Comment by LukasCBossert** [comment]
ah - klar. das habe ich nicht gesehen gehabt. ich habe nun die zwei Stellen zusammengezogen. Zugleich habe ich eine Umgebung an dieser Stelle eingebaut, mit der man Code und Text nebeneinander anzeigen lassen kann.

**Comment by thomas-hilarius-meyer** [comment]
... dann ist ja der Fall erledigt.
<Aufräumwut...>
