### ISSUE TITLE
Gliederung

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#35]
Ich will nicht in fremden Texten herumwursten, deshalb schlage ich das als issue vor:

Den Abschnitt "Kataloge erstellen" würde ich zur "Section" degradieren, das Kapitel würde ich "Integration von LaTeX in heterogene Projekte" oder so nennen.
Dann gibt es Unterkapitel / sections:
- Zusammenarbeit mit Python: Kataloge erstellen
- Zusammenarbeit mit Perl: eine Kurzfassung von meinem Zeugnis-Artikel aus DTK 2015/1
- weitere Beispiele...

Weil dies über die Grenzen von LaTeX hinausgeht, würde ich das ganz an den Schluss stellen, nach beamer und der LaTeX-Dokumentation.

Ich passe mal die README-Datei an.

Bitte äußert Eure Meinung!

**Comment by UweZiegenhagen** [comment]
Find ich gut, Uwe

**Comment by LukasCBossert** [comment]
An sich stimme ich dem zu, aber bspw. das Erstellen von Katalogen hat zunächst nichts mit Python zu tun, sondern ist eine TeX-genuine Lösung. Python kommt nur für das eine Zusatzfeature zum Einsatz, wenn man die Rückverweise der Katalogeinträge auf die Seite des Fließtextes haben möchte.

Daher würde ich das Kapitel/section mit der Katalogerstellung ohne Python beschreiben (das ist schon etwas high-end und für die meisten Geisteswissenschaftler meine ich ohne Belang); dann wäre die Zuordnung zu "Integration von LaTeX in heterogene Projekte" nicht ganz korrekt.

**Comment by UweZiegenhagen** [comment]
Stimmt auch wieder, aber gehört "Kataloge" nicht vllt. besser zu "Index & Co" mit einem Verweis: "Für eine alternative Lösung über Python siehe Abschnitt x.y"

**Comment by LukasCBossert** [comment]
Dann würde man "Kataloge" auftrennen - die Python-Sache kommt zu "Integration von LaTeX in heterogene Projekte" und "Katalogerstellung" zu .... hm, Index & Co scheint mir auch nicht ganz treffend zu sein, denn es wird ja nichts aus dem Fließtext generiert, sondern etwas Eigenständiges geschaffen, das unabhängig vom Fließtext ist. 
Naja, ich werde den Abschnitt mal schreiben, dann können wir ihn immernoch hin und her schieben (tut mir leid, dass dieses Thema "KAtalog" mir so am Herzen liegt, aber für einige geisteswissenschaftliche Bereiche ist so ein Katalog unerlässlich und ich habe lange gebraucht, bis ich die richtige Lösung gefunden hatte - dieses Suchen will ich unseren Lesern ersparen).

**Comment by thomas-hilarius-meyer** [comment]
Ab in den Orkus mit Dir, Issue 35!
