### ISSUE TITLE
Guideline zur Code-Dokumentation

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#37]
Haben wir uns denn jetzt auf die Dokumentation von längerem LaTeX-Code geeinigt?

Ich denke, es gibt drei Fälle:

1. Nur Listing wiedergeben (in voller Satzspiegelbreite)
-> am einfachsten wohl mit \begin{lstlisting}

2. Listing neben Output-Seite, jeweils halbe Breite

3. Listing, gefolgt von Output

Wie realisieren wir Nr. 2 und 3?
LTXexample hat ja, wie deutlich erkennbar, Probleme mit Umlauten.
Gibt es einen Weg, der den Output automatisch erzeugen kann?

Ansonsten müssten wir den Weg wie im exam-Kapitel gehen...

**Comment by baem2** [comment]
Also hier: #3 ist `tcolorbox` vorgeschlagen worden, das ist auch schon im Code gelandet: 52db9ce

**Comment by LukasCBossert** [comment]
Ich habe in der Wiki die drei Varianten schon beschrieben (https://github.com/thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler/wiki/Code-|-Code-&-Ausgabe-|-Ausgabe) 
Sie sind auch schon im Code - man kann und muss das Design noch anpassen (aber das ist ja dann global möglich).

**Comment by thomas-hilarius-meyer** [comment]
Ach Mensch, lesen müsste man können...

Ich baue das noch in die GUIDELINES ein, was mir persönlich mehr entgegenkommt, da ich oft ohne LAN auf dem Laptop arbeite.

..und tschüss, issue!
