### ISSUE TITLE
Autormarkierung

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#38]
Ich schlage vor, dass wir den Autor von Kapiteln, Sections etc. mit dem Makro \autor{} bezeichnen.

Es bleibt zu überlegen , wie das sinnvoll umzusetzen ist...

**Comment by LukasCBossert** [comment]
gut, dann kann man ggf. zugleich eine indizierung darüber laufen lassen. 
wie wäre es mit \paketautor[AUTOR]{Paketname} dann hat man die immer gleich zusammen.

**Comment by sieversMartin** [comment]
> Ich schlage vor, dass wir den Autor von Kapiteln, Sections etc. mit dem Makro \autor{} bezeichnen.
Ja, ich hätte auch so etwas vorgeschlagen. Das kann man dann auch mit anderen Paketen wie `pdfcomment` kombinieren.

> wie wäre es mit \paketautor[AUTOR]{Paketname}  ...

Warum `\paketautor`? Ich dachte, es geht hier um uns als Autoren?

**Comment by sieversMartin** [comment]
Alternativ zu `\autor` könnte man auch `\martin`, `lukas` oder auch `thomas` definieren.

**Comment by thomas-hilarius-meyer** [comment]
Ja, ich dachte an UNS aus Textautoren.
Das Erschließen von Paketautoren finde ich fast unnötig, denn die wenigsten werden ein Paket so aussuchen: "Hmm, heute möchte ich mal ein Paket von Roger Moore benutzen. Der schreibt ja sooo attraktive Paketdoku..."   -- Spaß beiseite!

Wobei man sich ernsthaft fragen sollte, ob wir namentlich markierte Unterabschnitte wollen, oder einen Kollektivtext produzieren. Ich glaube, ich wäre für ersteres.

**Comment by LukasCBossert** [comment]
aha - tut mir leid, das hatte ich dann missverstanden. 
es würde ja `\martin` etc reichen ...

**Comment by UweZiegenhagen** [comment]
Bin für ersteres

Von meinem iPhone gesendet

**Comment by thomas-hilarius-meyer** [comment]
Das ist eigentlich auch erledigt...
