### ISSUE TITLE
pdf-Inhaltsverzeichnis

### ISSUE THREAD

**Issue by baem2** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#39]
Ich hab mal wieder eine Frage zu unserem Projekt: Welches der verwendeten Pakete sorgt dafür, daß in der pdf eine Gliederung angezeigt wird, mit der man zu den Seiten springen kann (also nicht das Inhaltsverzeichnis, sondern die Gliederung in der Seitenleiste). Ist das hyperref?

**Comment by LukasCBossert** [comment]
Was ist denn für dich die Seitenleiste? ansonsten würde ich sagen, liegt das an `hyperref`

**Comment by sieversMartin** [comment]
Ja, auch die Gliederung (bookmarks) wird von `hyperref` erzeugt. Aufklapptiefe und Nummerierung lassen sich konfigurieren.

**Comment by LukasCBossert** [comment]
ah, im PDF-Viewer :) neben `hyperref` sorgt auch das Paket `bookmarks` dafür, dass u.a. nur ein Kompilierdurchgang notwendig ist, um TOC und Seitenleiste zu aktualisieren (ansonsten ja immer zwei Durchgänge).

**Comment by baem2** [comment]
Okay, danke!
