### ISSUE TITLE
Kritische Editionen mit reledmac

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#4]
Wer hat schon echte Erfahrungen mit der Erstellung kritischer Editionen mit (r)eledmac?

Ich selber habe in einem früheren Leben mehrere kritische Editionen betreut, aber (noch) nicht mit LaTeX, sondern mit Tustep.

Ich würde mich schon gerne in reledmac einarbeiten, aber vielleicht haben wir einen Experten, der das Skript schreibt? Dann geht nämlich meine Einarbeitung auch besser, hehehe...

**Comment by baem2** [comment]
Ich schreibe gerade einen DTK-Artikel zu genau diesem Thema. Wenn der fertig ist, kann ich den gerne hier mit reinstellen (ähem, je nach Copyrightlage bei der DTK) oder für den hiesigen Zweck anpassen.

**Comment by LukasCBossert** [comment]
bzgl copyright gibt es kein problem. da ist die dtk anders als unsere fachzeitschriften.

--- gesendet von unterwegs ---

**Comment by thomas-hilarius-meyer** [comment]
Wäre es eine Option, Deinen Artikel - ggf. kannst Du ihn vielleicht etwas anpassen - in das Skript zu übernehmen? Selbstverständlich mit sauberer Verfasserangabe etc. ...

Ich fände das cool.

**Comment by baem2** [comment]
Klar, sehr gerne. Und das Copyright scheint ja, wie Lukas sagt, auch kein Problem zu sein ...

**Comment by LukasCBossert** [comment]
Ja, Herbert hat mir versichert, dass man nachwievor die Rechte an seinem Artikel hat - daher kann man damit machen was man möchte, zumal nur der Inhalt in dieses Skript übernommen werden soll.

**Comment by sieversMartin** [comment]
Ja, Rechte sind überhaupt kein Problem. Zum Thema kritische Editionen. Ich arbeite selber auch seit einiger Zeit mit (r)eledmac und kann evtl. noch etwas beisteuern.

**Comment by baem2** [comment]
So, ich bin noch git-unerfahren und hab deswegen mal die reledmac-arbeiten in einen eigenen Entwicklungszweig (namens "reledmac") getan, da kann ich dann nicht viel kaputt machen; sobald ich dann einigermaßen fertig bin, werde ich das in den Hauptzweig mergen.

(Allerdings schreib ich jetzt erstmal den DTK-Artikel fertig, das wird noch dauern.)

**Comment by thomas-hilarius-meyer** [comment]
Aber auch diesen Issue kann ich dann ja aufräumen...
