### ISSUE TITLE
Große und kleine Werkzeuge

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#40]
@ Philipp: Vielen Dank für die Anmerkungen und dafür, dass Du den Text wieder zum Laufen bekommen hast. Ich hatte auf die Schnelle kein TeX und hab nur via Firefox in den Dateien rumgewurstelt....

Ein Punkt, über den wir uns einig werden sollten:
Stellen wir Pakete wie parallel, lineno und manyfoot (und einige andere Kandidaten) vor, oder streichen wir die generell und nutzen für alle die einschlägigen Funktionen von reledpar / reledmac?

Ich denke, für beide Positionen gibt es gute Argumente; mein Standpunkt war bisher, lieber die Einzellösungspakete zu besprechen. Jetzt habe ich aber z.B. die Zickerei von parallel erlebt...

Für die Einzelpakete spricht, dass wir ja eine Anleitung zu LaTeX schreiben, nicht zu reledmac. Auch werden die meisten Zeilennummern ODER Paralleltexte ODER zwei Fußnotenapparate brauchen, eher wenige das alles zusammen für eine große kritische Ausgabe.

Nimmt man den Porsche, um zum Aldi zu fahren, oder den Golf?
Andererseits: Wenn man den Prosche hat, warum sollte man dann noch DAZU einen Golf kaufen?

**Comment by LukasCBossert** [comment]
ich stelle mir vor, dass die Erläuterung möglichst am konkreten Beispiel erfolgen soll, sodass diese Pakete bei reledpar/reledmac ihren Platz haben können. ggf. könnte man einen kleinen Absatz zu Beginn der Einführung der Pakete zum allgemeinen Gebrauch schreiben. Ansonsten aber ihre Funktionsweise für reledmac etc.

**Comment by baem2** [comment]
Ich denke, man sollte das von Paket zu Paket abwägen.

`lineno` kenn ich nicht, aber es ist sicher sinnvoll, das vorzustellen, wenn man einfach nur Zeilennummern haben will -- da wäre ´reledmac´ ein bißchen groß ... (man kann ja trotzdem nach hinten verweisen, daß man auch mit reledmac einfach Fußnoten machen kann).

`manyfoot` kenne ich auch nicht; aber wenn man mehrere Fußnoten-Apparate braucht, würde ich gleich `reledmac` nehmen; denn dann ist die kritische Ausgabe auch nicht mehr weit und das ist ja eh einer Kernfunktion von `reledmac`

`parallel` kenne ich und würde ich ganz streichen: Es wird seit 13 Jahren nicht weiterentwickelt und hat Fehler. Hier muß man ja nicht einmal `reledmac` laden, `reledpar` reicht, und die Funktionsweise (also was die Befehle angeht) ist sehr ähnlich wie bei `parallel` (also vor allem: `parallel` ist nicht irgendwie einfacher zu bedienen oder so).

**Comment by arktisvogel** [comment]
Meine Überlegungen zur `lineno` sagen mir dass, einen WissenschaftlerIn benutzt einen bestimmte Paket für Ihrem Zweck. Da es oft die Möglichkeit gibt, mit diesem Paket, einen Parameter zu setzen was Zeilennummerierung automatisch erledigt wäre alle andere Diskussionen überflüssig.

Die Idee, jeweils einen Abschnitt zu schreiben, massgeschnitten auf bestimmte Fachbereiche finde ich am sinnvollsten.

**Comment by thomas-hilarius-meyer** [comment]
Vielen Dank für Eure Meinung.

Ich halte fest:
- LINENO behält seinen kurzen Abschnitt in texte.tex, dazu kommt ein Querverweis auf RELEDMAC
- MANYFOOT dito.
- PARALLEL fliegt ganz raus; der Absatz verweist auf reledPAR. (Dieser Textteil wird ja aber nicht mehr von mir verantwortet...)
