### ISSUE TITLE
lfgw-musterdatei...

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#41]
... war natürlich nur Schrott, aber zum Einbinden wird sie doch gebraucht.

Wo ist sie hin?

An sich finde ich die Idee immer noch gut, EINEN einzigen, WINZIGEN Text zu geben, bei dem wir "mal so richtig zeigen, was wir können", d.h. der ein Register hat, Parallestellen, Interlinearglossen und und und...

**Comment by baem2** [comment]
Das war wahrscheinlich ein Unfall: 8fa7451

**Comment by thomas-hilarius-meyer** [comment]
Fall erledigt, kompilieren klappt wieder...
