### ISSUE TITLE
Kapitelfusion?

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#42]
Ich möchte doch nochmal die Diskussion eröffnen, ob man nicht Kap. 4 (Interlinearglossierung) und 5 (Texte parallel setzen) zusammenfassen sollte.

Es geht doch um dasselbe: Zwei Textformen (Original + Übersetzung, Vorlage + Bearbeitung, Text + Kommentierung/Glossierung, ...) nebeneinander zu stellen.

Könnten wir daraus nicht ein Kapitel machen, etwa "Zusammengehörende Texte parallelisieren" oder so?

**Comment by baem2** [comment]
Jo, die Teilung hab ich vor allem zur einfacheren Abgrenzung der Zuständigkeiten gemacht. Ich denke zwar, daß es sehr große Unterschiede gibt und die Anwendungsszenarien der beiden Abschnitte sehr weit auseinander gehen werden (es ist ein großer Unterschied, ob man Texte horizontal oder vertikal parallelisiert ...), aber: Man kann es aber schon alles in ein Kapitel packen.

Von daher: Nur zu.
