### ISSUE TITLE
Werbung auf der Meta-Ebene

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#45]
Liebe Mitstreiter,

ich knoddele gerade meinen DTK-Artikel über das Erstellen von Bibelstellenregistern fertig, da kommt mir eine Idee:

Was haltet Ihr davon, wenn wir in der DTK 2017/1 einen kleinen Artikel über "LaTeX für (nichtmathematische) Geisteswissenschaftler" einstellen und unser Vorhaben kurz vorstellen?

Ich habe das Gefühl, dass uns immer noch in manchen Bereichen wirkliche Experten-Nutzer fehlen (z.B. Arabisch, Kurzschriften, ...). Vielleicht finden sich noch mehr Mitarbeiter?

Oder habt Ihr das Gefühl, dass mehr Mitmacher eher den Prozess verlangsamen werden? (Gesetz von Moore, da war doch was...)

Herzliche Grüße
Thomas

**Comment by sieversMartin** [comment]
Am 27.12.2016 um 09:49 schrieb Thomas Hilarius Meyer:
> Liebe Mitstreiter,
> 
> ich knoddele gerade meinen DTK-Artikel über das Erstellen von
> Bibelstellenregistern fertig, da kommt mir eine Idee:
> 
> Was haltet Ihr davon, wenn wir in der DTK 2017/1 einen kleinen Artikel
> über "LaTeX für (nichtmathematische) Geisteswissenschaftler" einstellen
> und unser Vorhaben kurz vorstellen?

Eine gute Idee. Zusätzlich/Alternativ wäre auch eine Vorstellung auf der
DANTE-Tagung in Zeuthen möglich.

> Ich habe das Gefühl, dass uns immer noch in manchen Bereichen wirkliche
> Experten-Nutzer fehlen (z.B. Arabisch, Kurzschriften, ...). Vielleicht
> finden sich noch mehr Mitarbeiter?
>
> Oder habt Ihr das Gefühl, dass mehr Mitmacher eher den Prozess
> verlangsamen werden? (Gesetz von Moore, da war doch was...)

Die grundsätzlichen Fragen sind vermutlich "Wie umfangreich soll das
Werk thematisch und von der Seitenzahl her werden?" und "Wann wollen wir
es als 'fertig' deklarieren?" Mehr Mitstreiter erfordern vermutlich ein
strengeres Regiment, wenn man in absehbarer Zeit etwas fertig haben möchte.

> Herzliche Grüße
> Thomas


-- 

Martin Sievers -- Einfach schöner publizieren

Im Alten Garten 5
54296 Trier

Telefon:  +49 (0) 651 4936567-0
Telefax:  +49 (0) 651 4936567-9
Mobil:    +49 (0) 179 7347726

Internet: http://www.schoenerpublizieren.de
E-Mail:   info@schoenerpublizieren.de

**Comment by thomas-hilarius-meyer** [comment]
Dann fabriziere ich 'mal einen kurzen Text für die DTK. Ich stelle ihn mir im wesentlichen als eine kommentierte Gliederung von LFGW vor.

2 Fragen:

- Darf ich Eure Namen als Projektmitarbeiter nenen?
- In welchen Bereichen brauchen wir denn noch Unterstützung?

**Comment by LukasCBossert** [comment]
Mich kannst du gerne nennen. Ich denke wir könnten Unterstützung in dem Sinne brauchen, dass Leute ihre Pakete/Makros nennen (am besten mit einem erläuternden Text), die sie (im geisteswissenschaftlichen Bereich) für wichtig erachten.

**Comment by UweZiegenhagen** [comment]
Gute Idee. Ich bin auch in Zeuthen, Martin sicher auch. 

Uwe

--
www.uweziegenhagen.de

**Comment by baem2** [comment]
Mich kannst Du gerne nennen.

**Comment by thomas-hilarius-meyer** [comment]
ICh habe den Ordner "nebentexte" angelegt für derartige Texte, die dazugehören, aber nicht ins Buch kommen.

Darin befindet sich mein allererster Entwurf.
Ich komme vor heute abend nicht mehr dazu, daran was zu machen.

Tobt Euch aus ...

**Comment by baem2** [comment]
Dann mache ich hier mal wieder auf, zwecks Kommentaren:

Zu meinem commit: Es gibt auch andere Möglichkeiten als (re)ledmac oder TUSTEP. Für TeX zB http://www.webdesign-bu.de/uwe_lueck/ednworks.html, für Word-Freunde CTE: http://cte.oeaw.ac.at/ -- deshalb hab ich TUSTEP da mal rausgenommen ...
