### ISSUE TITLE
LaTeX für Arbeitsgruppen

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#5]
Sollten wir eine kurze Diskussion der verschiedenen Möglichkeiten aufnehmen, wie man in einer Arbeitsgruppe gemeinsam Dokumente erstellt.

Am eigenen Beispiel: Ich "lerne" jetzt erst Git, hätte sonst mit overleaf gearbeitet, was immerhin auch schon etwas ist...

Ich kann mir vorstellen, dass viele Leser (z.B. ich!) für eine kurze Anleitung zu Git dankbar wären, auch wenn es auf den ersten Blick off topic ist.

Die Zielgruppe unseres Skripts will LaTeX nutzen, weil sie bestimmte typographische Bedürfnisse hat. LaTeX ist neu und evtl. fremd für sie und nicht eingebettet in einen ganzen Orbit schon bekannter Software wir Git etc. Deshalb sollte man auf dieses "Umfeld", das im Alltag erst richtig effizientes Arbeiten (z.B. in einer Arbeitsgruppe) erst möglich macht.

**Comment by LukasCBossert** [comment]
Finde ich sehr gut. Ich nutze Github für verschiedene Arbeitsgruppen und die Leute kommen nach einer kurzen Erklärung ganz gut damit klar. 
Es gibt dann auch einen speziellen ›Education-Account‹, den man mit einer Email beantragen kann. Damit kann man private Respositorien erstellen, sodass man seine Hausarbeit, Abschlussarbeit, Promotion etc. über Github versionieren und speichern kann.

**Comment by baem2** [comment]
Das Thema Versionsverwaltung sollten wir auf jeden Fall aufgreifen, denn diese Möglichkeit ist ein großer Vorteil von TeX ggü. anderen Programmen. Gerade bei Projekten mit mehreren Mitarbeitern ist das super.

Ich selbst verwende subversion und finde das auch ziemlich geeignet für derartige Projekte, weil es nicht so komplex wie git ist (Stichwort: zentrales repository). git ist meines Erachtens eher für Programmier-Projekte geeignet, wo alle Teilnehmer auf der technischen Ebene genau wissen, was sie tun.

Bei geisteswissenschaftlichen Projekten werden die meisten Mitarbeiter keine Ahnung von branches und mergen haben, da ist die lineare Struktur von (beispielsweise) svn deutlich einfacher zu erklären und handhaben ...

**Comment by UweZiegenhagen** [comment]
Kann ich gern übernehmen, zu svn habe ich fertige Texte.

Uwe

--
www.uweziegenhagen.de

**Comment by LukasCBossert** [comment]
bin sehr gespannt!!

**Comment by baem2** [comment]
Also da es hier keinen Einspruch gab und @UweZiegenhagen für svn eh schon Sachen bereit hat, würde ich sagen, daß wir also einen Abschnitt über Versionsverwaltung am Beispiel svn machen? Ich assigne mal an Uwe.

**Comment by UweZiegenhagen** [comment]
Ok

Von meinem iPhone gesendet

**Comment by thomas-hilarius-meyer** [comment]
Wunderbar, auch dieser issue ist erledigt.
Mann, was haben wir schon alles geschafft.... ;-)
