### ISSUE TITLE
Packages ins LitVz

### ISSUE THREAD

**Issue by baem2** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#54]
In der DTK gibt es eine eigene bib-Klasse "ctan", damit kann man dann die wichtigsten Angaben zu den verwendeten Paket-Versionen unterbringen. Sollen wir das auch machen oder zB in einer Fußnote auf die verwendete Version hinweisen?

**Comment by thomas-hilarius-meyer** [comment]
Also, ehrlich gesagt, halte ich das für overkill...

**Comment by UweZiegenhagen** [comment]
Ja, wann genau soll die Information nützlich sein. Kann ja innerhalb von Tagen hinfällig sein.

Uwe

**Comment by baem2** [comment]
Jo, auch wahr ...
