### ISSUE TITLE
Gliederungsänderung

### ISSUE THREAD

**Issue by baem2** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#55]
Da reledmac und reledpar eng verwandt sind, ist es sinnvoll, reledpar nach reledmac vorzustellen. Daher hab ich die Reihenfolge in der Gliederung geändert: erst Kritische Apparate, dann Parallele Texte ...

Falls es Meinungen dazu geben, sollte kann das hier diskutiert werden ...

**Comment by thomas-hilarius-meyer** [comment]
Schweigen heißt - glaube ich - Zustimmung...

**Comment by baem2** [comment]
Jo, so hab ich das auch gedeutet ... :)
