### ISSUE TITLE
Zählweisen von Beispielen

### ISSUE THREAD

**Issue by AKielhorn** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#57]
Wir haben drei unterschiedliche Zähler für Beispiele:

- lfgwcode
- lfgwexample
- lfgwprint

Die Zähler sind unabhängig, wenn es in einem Kapitel sowohl `code` als auch `example` gibt,
laufen die Zähler durcheinander.

code 2.1
code 2.2
example 2.1
code 2.3

Ein gemeinsamer Zähler für alles wäre meiner Meinung nach günstiger:

code 2.1
code 2.2
example 2.3
code 2.4

Gibt es Einwände dagegen?

**Comment by LukasCBossert** [comment]
nein, kein Einwand. Man könnte/müsste noch ein entsprechendes `label` für die Listen definieren, was ich aber für ´tcolorbox` bzw. für `lfgwcode` etc nicht hinbekommen habe, sodass das leere Klammerpaar bei 
```
\begin{lfgwcode}{}
```
nicht nutzlos ist.

**Comment by baem2** [comment]
Das ist jetzt ja, soweit ich sehe, erledigt.
