### ISSUE TITLE
Xe(La)TeX?

### ISSUE THREAD

**Issue by tonnerkiller** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#58]
Hallo,
ich bin grad über die Mailingliste auf das Projekt aufmerksam geworden und frage mich, ob nicht Xe(La)TeX in den Teil mit den fremden Sprachen reingehören sollte/könnte.

In meinem Studium (Ev. Theologie) hab ich damit gearbeitet, um griechische und vor allem hebräische Texte einzugeben. Davor hatte ich eine Arbeit mit ibycus4 geschrieben, allerdings ließen sich die griechischen Passagen nicht sinnvoll per copy&paste entnehmen für andere Zwecke. Für hebräische Texte hatte ich kein Paket gefunden, das die Eingabe aller Akzente zuließ, wahrscheinlich hätte cjhebrew sogar gereicht, aber das konnte ich am Anfang des Studiums nicht richtig einschätzen.

So kam ich auf Xe(La)TeX, was mir ein guter Ansatz auch für ganz verschiedene andere Sprachen erschien. Womöglich kommt es da an seine Grenzen, wo es für Keilschrift kein Keyboardlayout gibt oder so...

**Comment by baem2** [comment]
Hi & willkommen!

Wir haben uns gegen XeTeX entschieden, weil es nicht mehr weiterentwickelt wird und keine (großen?) Vorteile gegenüber pdflatex/LuaLaTeX bietet. Griechisch/Hebräisch ist heute (auch in UTF-8) mit pdflatex und LuaLaTeX möglich ...

**Comment by tonnerkiller** [comment]
Danke für die Info.
