### ISSUE TITLE
Interlinearübersetzungen

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#6]
Ich bin mit dem Paket covington zur Erstellung von Wort für Wort-Übersetzungen ziemlich unglücklich.

Es produziert bei mir seltsame Warnmeldungen und ist steinalt.

Weiß jemand eine Alternative?

**Comment by baem2** [comment]
Ich habe für "Glossierungen" mal https://www.ctan.org/pkg/gb4e verwendet, suchst Du sowas?

**Comment by thomas-hilarius-meyer** [comment]
Ja, das sieht sehr gut aus.

**Comment by baem2** [comment]
Zum Thema "Texte parallel setzen" würde ich vorschlagen, auf reledpar zurückzugreifen, denn das kommt dann im nächsten Kapitel ja sowieso noch ...

**Comment by baem2** [comment]
Ist das in Ordnung, wenn ich das Kapitel "Texte parallel setzen" aufteile in zwei Abschnitte: Einer zur Interliniearglossierung und einen zu parallelen Texten in Spalten oder im zweiseitig?

**Comment by thomas-hilarius-meyer** [comment]
Aber ja, natürlich ist das ok.

Ich dachte ja ursprünglich sogar dreiteilig:
I - wortebene
II - Ebene von Absätzen oder Versen
III - Fließtext auf Seiten/Spaltenebene

Ich sehe auch, dass II und III zusammenwachsen...

Willst Du das ganze Kapitel übernehmen und dann auch parallel - das ja
offensichtlich zickt - raustun und durch reledpar erssetzen?

Am 3. Dezember 2016 um 07:51 schrieb Philipp <notifications@github.com>:

**Comment by baem2** [comment]
Also um Spalten/zweiseitig kann ich mich gerne kümmern; dabei wird auch berücksichtigt, daß Absätze parallel stehen.

Soweit ich weiß, kann reledpar auch mit Versen umgehen, das hab ich allerdings noch nie gemacht.

Von Glossierungen habe ich nicht so die Ahnung.

Ich kümmer mich also erstmal um Spalten & zweiseitigen Satz, alles weitere sehen wird dann.

**Comment by thomas-hilarius-meyer** [comment]
Ich stelle den Abschnitt auf gloss4e um und schließe diese Diskussion.
Vielen Dank für den Tipp!

Amen. :-)
