### ISSUE TITLE
lualatex

### ISSUE THREAD

**Issue by UweZiegenhagen** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#60]
Hi zusammen,

in der ersten Zeile des Hauptdokuments stand ja noch pdflatex als Engine, damit bricht aber der LaTeX Lauf ziemlich schnell ab. Ich habe die Zeile mal entfernt, sodass LuaLaTeX genutzt wird, ist das okay für euch?

Uwe

**Comment by thomas-hilarius-meyer** [comment]
Oja, ich habe eigentlich immer lualatex zum Übersetzen benutzt!

Ich bin fast fertig mit dem Diagramme-Abschnitt; wie stehen denn die Aktien bei Euch?

**Comment by thomas-hilarius-meyer** [comment]
Eigentlich ist das ja erledigt.
