### ISSUE TITLE
Codebsp ==> Beispiel

### ISSUE THREAD

**Issue by UweZiegenhagen** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#61]
Hi zusammen,

stört es euch, wenn wir aus "Codebsp." einfach nur Beispiel machen?

"Codebsp" ist m.E. falsches Deutsch, es müsste wenn schon "Code-Bsp." heißen, die Abkürzung sieht aber auch doof aus. "Beispiel" klingt neutral, dass es kein Foto- oder Musik-Beispiel ist, sollte für den Leser ersichtlich sein.

Uwe

**Comment by thomas-hilarius-meyer** [comment]
gerne!

**Comment by UweZiegenhagen** [comment]
Ok, erledigt.
