### ISSUE TITLE
Wer von euch kommt nach Zeuthen?

### ISSUE THREAD

**Issue by UweZiegenhagen** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#62]
Wer von euch kommt denn zur Tagung nach Zeuthen?

Uwe

**Comment by thomas-hilarius-meyer** [comment]
nein, leider nicht...

**Comment by LukasCBossert** [comment]
Ich komme leider nur am Freitag, dafür aber auch zum abendtreff

Von meinem iPhone gesendet

**Comment by sieversMartin** [comment]
Ich bin dabei (wenig überraschend ;-) )

**Comment by baem2** [comment]
Ich komm auch am Freitag inkl. abends.

**Comment by arktisvogel** [comment]
Ich komme nicht.
