### ISSUE TITLE
Stand der Dinge

### ISSUE THREAD

**Issue by baem2** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#63]
Um dieser Anregung (https://github.com/thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler/issues/60#issuecomment-282779144) eine eigene issue zu geben: Wie sieht's aus, was fehlt, wer hat noch was vor?

Also meine Abschnitte (5. und 6.2) sind bis auf ein paar Kleinigkeiten fertig. Wenn jemand weiß, wie das geht, könnte man die übersetzten Beispiele aus 5. vielleicht im Druck noch besser hervorheben (Umgebung reledmacbsp, definiert in kritischeApparate.tex).

**Comment by UweZiegenhagen** [comment]
Ich werde in den nächsten Wochen wieder verstärkt was machen, anfangen werde ich mit dem exam Kapitel.

**Comment by baem2** [comment]
Achso, zu überlegen ist noch, ob ich für den Parallele-Seiten-Satz noch wie in dem Aufsatz in der aktuellen Komödie als Beispiel eine Doppelseite im Querformat einbinde ...

**Comment by AKielhorn** [comment]
Fände ich gut, so sieht man schnell was möglich ist.

**Comment by thomas-hilarius-meyer** [comment]
ja, da bin ich unbedingt dafür.

**Comment by baem2** [comment]
Jut, dann werd ich das noch einfügen.

**Comment by baem2** [comment]
Ich hab noch ein kleines Beispiel eingefügt, da ist allerdings noch Luft nach oben (mal schauen, wozu ich noch so komme ...).

**Comment by baem2** [comment]
So, nach stundenlangem debugging kommt also der reledmac-Teil dem "Fertigsein" nahe. Jetzt muß ich nur noch schauen, ob man die Beispiele schöner umgesetzt bekommt (mit lfgwprint scheint das Gr. nicht so zu gehen).

Wie sieht es denn sonst so aus? Was denkt ihr, wie weit Eure Abschnitte sind, wie viel Zeit Ihr noch braucht etc?

**Comment by baem2** [comment]
So, liebe Leute, wie schaut es aus? Wollen wir einen "Minimalbestand" definieren und auf den hinarbeiten sowie eine  Frist setzen, und was bis dann nicht fertig ist, rauswerfen? Oder warten wir einfach weiter, was passiert?

**Comment by UweZiegenhagen** [comment]
Ich brauch noch bis Ende Juli, bin aber konfident, dann fertig zu sein.

**Comment by LukasCBossert** [comment]
beschämt muss ich zugeben, dass die Diss (neben den anderen Sachen, wie Familie) doch mehr Zeit in Anspruch nehmen: ich brauch auch noch Aufschub.

**Comment by baem2** [comment]
Das geht in #100 weiter.
