### ISSUE TITLE
Erste Zeile

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#65]
Wir die erste Zeile von lfgw.tex eigentlich irgendwie maschinell ausgewertet?
Das war mir nicht bewusst...

Ich habe bisher immer auf der Console gelatext mit 
lualatex --interaction=batchmode (*) lfgw

(*) nicht so fein, aber das compilieren dauert bei mir ca. 10 Minuten (sic!) und da will ich keine Unterbrechung wegen so Kinkerlitzchen wie fehlender Fonts ;-)

**Comment by UweZiegenhagen** [comment]
TeXworks, eventuell auch andere Editoren, sollten die auswerten können und die Engine automatisch setzen. Bei mir stürzt Texworks aber replizierbar ab, wenn ich den Compile Button drücke.

Ich werde mal eine kleine Batch Datei schreiben, die das automatisiert, bzw. ein make file.

--
www.uweziegenhagen.de

**Comment by sieversMartin** [comment]
> TeXworks, eventuell auch andere Editoren, sollten die auswerten können und die Engine automatisch setzen.

TeXstudio kann das z.B. auch. Ist in erster Linie natürlich dann praktisch, wenn Engine, Eingabekodierung und Sprache von den eigenen Standards abweicht und stellt sicher, dass immer das richtige verwendet wird. Wobei man für die Engine ja mit `\ifluatex` u.ä. eine Abfrage einbauen kann.

**Comment by baem2** [comment]
... und wieder was gelernt ... das werd ich gleich mal ausprobieren.

**Comment by thomas-hilarius-meyer** [comment]
Dann kann man das hier ja zumachen...
