### ISSUE TITLE
(lfgw.pdf) Irgendwie...

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#67]
...checke ich das nicht:

Ich habe in .gitignore lfgw.pdf geschrieben, damit es nicht immer aktualisiert wird (Diskussion letztens), jetzt ist es aber doch wieder da!

Wie verhindert Ihr denn das Hochladen des aktualisierten PDF's? 
Oder lualatext Ihr wirklich sol selten?

**Comment by UweZiegenhagen** [comment]
Ich werde es in tortoisesvn aus dem repo löschen und committen. Vermutlich klappt das ignore nur, wenn es nicht Teil des Repos war.

--
www.uweziegenhagen.de

**Comment by UweZiegenhagen** [comment]
Mit lualatex hat das übrigens nix zu tun...

--
www.uweziegenhagen.de

**Comment by thomas-hilarius-meyer** [comment]
Sorry, lieber Uwe, das war missverständlich formuliert. Ich meinte es so:

Immer wenn ich lualatex lfgw ausführe, wird ja mein lfgw.pdf durch eine neue Version ersetzt. Mein git bemerkt das - klar, dafür ist es ja da.

Wenn ich dann sage 
git commit -a -m "Wieder neuer Käse eingebaut"
git push
wird die PDF-Datei natürlich mit "kommitiert" und hochgeladen.

Warum passiert das bei Euch nicht?

**Comment by baem2** [comment]
Wenn man bei git commit das -a wegläßt und stattdessen am Ende einzelne Dateien nennt, dann pusht er später nur die.

**Comment by sieversMartin** [comment]
Genau dafür ist aber die Datei .gitignore

Die PDF muss aus dem Index entfernt werden "git rm lfgw.pdf" und in der .gitignore stehen.
Natürlich darf auch niemand anders die Datei wieder hochladen ;-)

**Comment by thomas-hilarius-meyer** [comment]
Himmiherrgottsakrament!
Jetzt habe ich gestern abend die Manpages von git meditiert und wollte genau das verkünden...
;-)

**Comment by baem2** [comment]
Achso, ich hatte bisher nicht begriffen, daß wir die lfgw.pdf völlig aus dem repository schmeißen wollen, dann geht das natürlich so.

**Comment by UweZiegenhagen** [comment]
Ich habe die Datei jetzt mal über TortoiseSVN rausgekickt und committed. Am Wochenende schau ich mal, wie ich die PDF Datei am besten bereitstellen kann. Eventuell publizier ich sie in einen neuen Ast und verlinke dann darauf. Schauen wir mal was Jenkins da bietet.
