### ISSUE TITLE
Neue Mitarbeiterin: Christine Römer

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#68]
Liebe Mitstreiter,

Christine Römer (treuen DTK-Lesern aus 2008 und 2016 bekannt...) hat sich bereit erklärt, den Abschnitt über "linguistische Baumstrukturen" (diagramme-zeichnen.tex) und "linguistische Beispiele" (texte.tex) zu schreiben.

Das ist ein großer Gewinn für unser Projekt.

Herzlich Willkommen!

Liebe Grüße
Thomas

**Comment by baem2** [comment]
Sehr schön! :)

**Comment by UweZiegenhagen** [comment]
Coole Sache!
