### ISSUE TITLE
Viva la musica! (?)

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#69]
Durch ein Update auf ctan habe ich gesehen, dass die Projekte um musictex etc. immer noch leben und präsent sind. Ich selber habe mal gezwungener Maßen ein paar Notenzeilen zu per Grafik eingebunden, die ich fertig geliefert bekam...

Sollten wir einen klitzekleinen Abschnitt zum Thema Notensatz einbauen? Und kennt sich jemand damit aus?

**Comment by sieversMartin** [comment]
Für Notensatz bietet sich Lilypond, dass man sehr gut in Verbindung mit TeX nutzen kann.

Ob das Thema ins Buch sollte? Ein klares Jein ;-)

**Comment by LukasCBossert** [comment]
Ich würde auch eher "nicht" sagen. Nicht, weil ich Musik nicht zu den Geisteswissenschaften zählen würde, sondern weil Musiker für Notensatz bereits eigene Programme haben, die sie nutzen würden.

**Comment by UweZiegenhagen** [comment]
Denk ich auch. Für mich sprengt das dann doch den Rahmen.

**Comment by thomas-hilarius-meyer** [comment]
Jo, überzeugt...

Zumal ich selber nur "Hänschen klein" mit einem Finger klimpern kann.
