### ISSUE TITLE
Datei aufteilen?

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#7]
Sollten wir inzwischen nicht vielleicht die Datei lfgw.tex in die einzelnen Kapitel aufteilen?

Dann sieht man besser, wer was wo geändert hat bzw. das macht es m.E. einfacher, für einzelne Dateien den jeweils zuständigen Autor zu definieren.

Vielleicht sollte die Aufteilung jemand machen, der sich mit git besser auskennt als ich...

**Comment by sieversMartin** [comment]
Mache ich gerne. Ich würde auch die Präambel separat anlegen und per `\input` einbinden.

**Comment by thomas-hilarius-meyer** [comment]
Ja, das wäre nett.
Danke!

**Comment by LukasCBossert** [comment]
ja, das halte ich für sehr sinnvoll, dann können primär einzelne Autoren an Kapiteln sitzen, die dann von anderen ergänzt werden.
