### ISSUE TITLE
jenkins ist jetzt aktiv

### ISSUE THREAD

**Issue by UweZiegenhagen** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#72]
Hi zusammen,

das PDF in "FinalesPDF" wird jetzt automatisch durch jenkins auf meinem Intel NUC erzeugt. Das bitte nicht verändern.

Viele Grüße aus Köln

Uwe

**Comment by thomas-hilarius-meyer** [comment]
Wow, vielen Dank!

Ich hab estmal in wikipedia studiert, was Jenkins eigentlich ist, und es sieht so aus, als hätten wir genau das gebraucht! Prima!

**Comment by baem2** [comment]
Sehr praktisch, danke!

**Comment by UweZiegenhagen** [comment]
Ich schreibe dazu grad mit Martin K. einen DTK Artikel: https://github.com/UweZiegenhagen/jenkins-latex

**Comment by baem2** [comment]
Geht hier weiter: #79
