### ISSUE TITLE
Abbildungen in ein Unterverzeichnis?

### ISSUE THREAD

**Issue by UweZiegenhagen** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#73]
Was haltet ihr davon, alle Abbildungen in ein entsprechendes Unterverzeichnis zu schieben? Das würde das Stammverzeichnis ein wenig übersichtlicher machen?

**Comment by thomas-hilarius-meyer** [comment]
Ja, das wollte ich auch schon mal machen, aber...

Gute Idee, Danke!

**Comment by LukasCBossert** [comment]
ja, unbedingt. und dann am besten über `\graphicspath{{...}}` ansteuern, sodass nur der Dateiname in der `figure`-Umgebung auftaucht.

**Comment by LukasCBossert** [comment]
wer macht und wie soll der Ordner heißen?

**Comment by UweZiegenhagen** [comment]
Am besten "Bilder" oder so. Am besten jeder seine eigenen Bilder.

**Comment by UweZiegenhagen** [comment]
Für Beispiele hatte ich das schon vor einer Weile eingerichtet.

**Comment by thomas-hilarius-meyer** [comment]
Habs gemacht...
