### ISSUE TITLE
lfgwcode und Griechisch

### ISSUE THREAD

**Issue by baem2** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#77]
Es gibt noch ein Problem mit unseren Beispiel-Makros und Griechis/UTF-8.

Wie zB in Beispiel 5.2 auf S. 83 (und allen folgenden Beispielen mit lfgwcode und Griechisch) in der aktuellen jenkins-pdf deutlich wird, macht er Umbrüche und Tabs, wo keine sein sollen etc. Weiß jemand Rat?

**Comment by sieversMartin** [comment]
Ich hatte vor einiger Zeit ähnliche Probleme und habe mir auch nur mit Workarounds helfen können ...

**Comment by baem2** [comment]
Und in welche Richtung gingen diese Workarounds?

**Comment by sieversMartin** [comment]
Ich wusste, dass die Frage kommt ;-)

Ich musste alle Leerzeichen "escapen":
``` latex
\begin{lstlisting}[escapechar=§]
§\null§εμπροσθεν§~§μου§~§γεγονεν§~§οτι§~§πρωτος§~§μου§~§ην:
```

**Comment by baem2** [comment]
Werd ich probieren, danke!

**Comment by baem2** [comment]
Super, das funktioniert (das Gute ist, es funktioniert, auch wenn man nicht kapiert, wieso ...). Danke!
