### ISSUE TITLE
jenkins

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#79]
Ich habe gerade die Bilder zum Lyrik-Teil nachgetragen; der LaTeX-Lauf bei mir war problemlos, die Ampel müsste grün sein.

Wann kommt denn das neue PDF?

Kontrolliert jenkins einmal die Stunde, oder müsste es schon da sein - aber die Ampel ist rot (warum auch immer? ich war's nicht... ;-)  )

**Comment by UweZiegenhagen** [comment]
Die Ampel im Bild bleibt rot, das war ein Handy Foto :-D

Ich lasse es aktuell um Mitternacht neu bauen, werde den git poll aber einbauen 

Von meinem iPhone gesendet

**Comment by sieversMartin** [comment]
> Ich lasse es aktuell um Mitternacht neu bauen

Kannst du Jenkins nicht so konfigurieren, dass kontinuierlich nach Änderungen gesucht wird und diese dann "sofort" umgesetzt werden?

**Comment by UweZiegenhagen** [comment]
Will ich einbauen, vermutlich heute Abend 

Von meinem iPhone gesendet

**Comment by UweZiegenhagen** [comment]
Ist jetzt auf halbstündigen GITpoll-Build eingestellt, schneller geht's auf der Maschine vermutlich nicht.

**Comment by baem2** [comment]
Also wie es aussieht, macht der nun halbstündig einen build, ohne zu checken, ob was geändert wurde? (Möglicherweise erkennt er seinen eigenen commit/push als Änderung an und geht deshalb immer davon aus, daß was geändert wurde?)

**Comment by thomas-hilarius-meyer** [comment]
Immerhin sehen unsere commit-Statistiken jetzt beeindruckend gut aus!
Wenn "Ihr" so weiter commitet, sind wir spätestens morgen fertig!

**Comment by UweZiegenhagen** [comment]
Hmm, also eine Lösung hab ich nicht

- Wir wollen das PDF im Github haben. 
- Upload geht nur per Checkin
- das dient wieder als Trigger für den nächsten Build

Ich kann die Datei auch per SSH irgendwo hinschieben, aber dann wäre es nicht mehr im Github.

**Comment by thomas-hilarius-meyer** [comment]
Jaja, das leuchtet irgendwie ein...
Aber unter diesen Vorraussetzungen ist es wahrscheinlich am sinnvollsten, die PDF - so wie Du es zuerst eingestellt hattest - einmal am Tag zu erstellen. Zu einer festen Zeit, sagen wir um 22 Uhr oder so. Es erstellt ja sowieso jeder dauernd zu Hause PDF's...

Es ist halt nur z.B. für mich praktisch, auch in der Schule einen Blick auf die PDF-Fassung werfen zu können. Dass die brandaktuell ist, ist m.E. nicht SOOO wichtig.

Das ist sowieso schon klasse - vielen Dank dafür!

**Comment by UweZiegenhagen** [comment]
OK, pass ich an.

**Comment by sieversMartin** [comment]
Vielleicht ist hier ja was dabei: https://github.com/Nerdwin15/stash-jenkins-postreceive-webhook/issues/173

Damit kann man bestimmte Nutzer bzw. Commits mit bestimmten Nachrichten ausschließen.
