### ISSUE TITLE
Zuständigkeitsbereiche

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#8]
Ich lege jetzt mal eine README-Datei an, in der ich die jeweiligen primären Zuständigkeitsbereiche notiere, die sich bisher ergeben haben...

**Comment by LukasCBossert** [comment]
Vielleicht mag sich jeder in die Kapitel eintragen, für die er/sie sich verantwortlich fühlt? 
Ich habe mich zu Literatur- und Verwaltung etc. eingetragen.

**Comment by thomas-hilarius-meyer** [comment]
JA, das ist prima. Die Eintragung sollte deshalb dann auch direkt in der README-Datei vorgenommen werden. Ich schließe deshalb diesen Issue jetzt.
