### ISSUE TITLE
philex

### ISSUE THREAD

**Issue by Christine-Roemer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#80]
Ich bin dabei, ein Kapitel "Belege einfügen mit philex" zu schreiben, dabei habe ich gemerkt, dass sich das Paket philex nicht mit den Festlegungen in "vorspann" verträgt.
Nachfolgendes Miniexample lässt sich mit lualatex problemlos kompilieren.
----------------------------------------------------
\documentclass{article}
\usepackage{philex}
\begin{document}
\lb{nice}{This is a nice day. \\ Not too hot.}
\end{document}
------------------------------------------------------
Die Verknüpfung mit "vorspann" jedoch nicht.
U.a. gibt es Probleme mit microtype.

Christine

**Comment by sieversMartin** [comment]
Kann ich so nicht bestätigen. `microtype` macht keine Probleme. Es ist vielmehr `siunitx`. Das Problem ist auf S. 18 in der Dokumentation zu `philex` erklärt samt Lösung:
```
\usepackage{linguex} %%% kann auch direkt philex sein
\def\fg{}
\usepackage{siunitx}
```

Das funktioniert bei mir.

**Comment by Christine-Roemer** [comment]
Danke. Es funktioniert, allerdings kommt noch eine Fehlermeldung, die sich auf covington.sty bezieht. Man kann sie aber mit enter übergehen:
(/usr/local/texlive/2016/texmf-dist/tex/latex/covington/covington.sty

! LaTeX Error: Command \ex already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.599 \newcommand{\ex}{\end{covexercise}}

Christine

**Comment by thomas-hilarius-meyer** [comment]
covington kann raus - das ist doch veraltet, oder?

**Comment by sieversMartin** [comment]
Der Fehler kommt durch einen Konflikt mit dem Paket `covington` zustande. Beide Pakete wollen `\ex` definieren. Das müssen wir vermutlich "aufbrechen"

**Comment by sieversMartin** [comment]
> covington kann raus - das ist doch veraltet, oder?

Umso besser

**Comment by Christine-Roemer** [comment]
"covington kann raus - das ist doch veraltet, oder?"

Ja, und fehlerhaft.

**Comment by sieversMartin** [comment]
Dann raus damit.
