### ISSUE TITLE
! LaTeX Error: No counter 'equationsave' defined.

### ISSUE THREAD

**Issue by UweZiegenhagen** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#81]
Kommt bei mir momentan als Fehlermeldung:

! LaTeX Error: No counter 'equationsave' defined.

**Comment by sieversMartin** [comment]
Kann ich nicht reproduzieren.

**Comment by UweZiegenhagen** [comment]
Lag an nicht aktuellen .aux Dateien
