### ISSUE TITLE
Kontaktadressen

### ISSUE THREAD

**Issue by baem2** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#83]
Wir sollten im Buch noch unsere Adressen hinterlassen, oder?

Wie ist da die Stimmungslage: Nur eMail oder die volle Adresse?

Und wohin?

**Comment by sieversMartin** [comment]
Evtl. kann man auch über Kurzbiographien nachdenken.

Bzgl. Adresse würde ich zur E-Mail plus ggf. Twitter etc. tendieren. Das ganze würde ich an den Anfang packen.

**Comment by LukasCBossert** [comment]
Ich denke auch wie @sieversMartin , keine wird uns ein Briefchen schreiben, daher reicht die Email-Adresse, bei Twitter bin ich leidenschaftslos. 
Die  bspw. ins Kolophon/Impressum?!

**Comment by baem2** [comment]
Kurzbiographie sind ne gute Idee! Ein Satz pro Nase oder so (Geburtsjahr + Job o.ä.?). Wahrscheinlich am besten auf der Rückseite der Titelseite?

**Comment by sieversMartin** [comment]
Aus meiner Sicht dürfen es auch zwei oder drei Sätze sein.

**Comment by UweZiegenhagen** [comment]
Denk ich auch, ich habe mal ein entsprechendes Teildokument angelegt.

**Comment by baem2** [comment]
... aber noch nicht commited?

**Comment by UweZiegenhagen** [comment]
Jetzt isses da.

**Comment by baem2** [comment]
Danke!
