### ISSUE TITLE
 Konstituentenstrukturen

### ISSUE THREAD

**Issue by baem2** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#85]
Aus der commit-message 59e6d8ab46d kopiere ich mal dies, damit es nicht untergeht:

> Die Datei läuft bei mir problemlos durch. Die eingangs auskommentierten Pakete bzw. Modifizierungen müssen dafür in vorspann.tex eingefügt werden.
> 
> Wo muss ich die Bibliografieeinträge einfügen?
> 
> Christine

Im vorspann kann einfach jeder seine Sachen unterbringen. Die bib-Einträge am besten in die lfgw-bibliographie.bib

**Comment by thomas-hilarius-meyer** [comment]
Ich habe den Teil eingebaut an der passenden Stelle und die Überschriften in die Hierarchie eingepasst, hoffentlich in Ihrem Sinne, Frau Römer!

Dabei ist mir aufgefallen, dass wir ein Problem in den Bereichen Katalog und Anhang haben, das ich nicht beseitigen konnte. (Allerdings war LaTeX bei mir mit leerer Eingabe zufrieden.) 
Kann mal gelegentlich jemand draufschauen?

**Comment by LukasCBossert** [comment]
Ich habe festgestellt, dass ich im geplanten Kapitel "Katalog" mit Kanonen auf Spatzen schieße und das, was ich zeigen möchte, besser anhand von `datatool` mache. Daher habe ich den bisherigen Ansatz in `katalog.tex` gelöscht und schreibe das Kapitel neu (ich hoffe bald mal zum Schreiben zu kommen). Löst es das Problem @thomas-hilarius-meyer ?

**Comment by thomas-hilarius-meyer** [comment]
Ehrlich gesagt hat sich nichts geändert...

Folgender Dialog spielt sich ab - bei Fragezeichen immer leere Eingabe:

[167]

! LaTeX Error: No counter 'equationsave' defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.55 \include{katalog}
                    
? 

! LaTeX Error: No counter 'covexercise' defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.55 \include{katalog}
                    
? 

! LaTeX Error: No counter 'equationsave' defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.57 \include{anhang}
                   
? 

! LaTeX Error: No counter 'covexercise' defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.57 \include{anhang}
                   
?

**Comment by LukasCBossert** [comment]
hm, `equationsave` konnte und kann aber nicht von `katalog.tex` kommen (die ist jetzt leer und hatte davor kein `equationsave`).

**Comment by thomas-hilarius-meyer** [comment]
Komisch, gell?
Ich versteh' da nix...

**Comment by LukasCBossert** [comment]
ist mir so auch schleierhaft.

**Comment by UweZiegenhagen** [comment]
Habt ihr mal die aux Dateien gelöscht? Macht im schlimmsten Fall mal einenfrischen checkout.

Uwe

--
www.uweziegenhagen.de

**Comment by Christine-Roemer** [comment]
@thomas-hilarius-meyer Könnten Sie bitte noch die vor ein paar Tagen hochgeladene Datei Linguistische "Belege_einfuegen" unter 2.21 in die Hauptdatei einfügen.

Christine

**Comment by thomas-hilarius-meyer** [comment]
habe ich erledigt...

- Übrigens läuft das ganze bei mir jetzt problemlos durch.
Computer haben Selbstheilungskräfte!

**Comment by Christine-Roemer** [comment]
Am 17.03.2017 um 21:49 schrieb Thomas Hilarius Meyer:
>
> habe ich erledigt...
>

Danke.
>
>   * Übrigens läuft das ganze bei mir jetzt problemlos durch.
>     Computer haben Selbstheilungskräfte!
>

Ahha, ich kenne nur, dass sie begrenzt lernfähig sind. ;-)

-- 
http://www.christine-roemer.de/
