### ISSUE TITLE
Konvertieren

### ISSUE THREAD

**Issue by baem2** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#87]
Hi,

ich hab gerade mal den aktuellen Stand vom Konvertieren-Kapitel angeschaut.

Ich hätte zwei "interaktive" Vorschläge dazu:
* Wäre es möglich, eine aussagekräftigere Überschrift zu nehmen?
* Der normale geisteswissenschaftliche Anwendungsfall wird ein Text mit ein paar Überschriften, Abbildungen und vor allem vielen Fußnoten sein. Könntest Du zu den einzelnen Tools anmerken, wie gut diese Dinge dann jeweils "ankommen"? (Zu den Fußnoten steht bisher nix.)

**Comment by AKielhorn** [comment]
Von WYSIWYG zu LaTeX

F: Wie macht man Fußnoten in Word?

A: Man erstellt ein Markdown Dokument mit Fußnoten, konvertiert das nach Word. Eh voilà.

Beide Programme kommen damit zurecht:
Die Anzahl der Fußnoten stimmt mit dem Original überein.
Trage ich nach.

**Comment by baem2** [comment]
Okay, vielen Dank!
