### ISSUE TITLE
Emacs Alias

### ISSUE THREAD

**Issue by AKielhorn** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#89]
Es ist zwar Off Topic, aber ich bin neugierig:

Wo sind diese Aliase definiert?
Wie kann man sie ändern, einen hinzufügen?

Schon so etwas einfaches wie :e für ë oder :i für ï geht nicht.

(Wenn man Evil benutzt kann man natürlich C-k :i eingeben, aber wir wollen die Leser und Leserinnen ja nicht unnötig verwirren:-)

**Comment by thomas-hilarius-meyer** [comment]
Ehrlich gesagt versteh ich nicht, was Du meinst.
Offenbar habe ich die letzte Zeit zu wenig LFGW gemacht...

**Comment by AKielhorn** [comment]
In texteUnicode wird die Eingabe von Sonderzeichen im Emacs beschrieben.
Dort gibt es zwei Beispiele für ñ und ç.
Ist übrigens vom 7. Dezember.

**Comment by thomas-hilarius-meyer** [comment]
Oh ja...

Diese Teile hat Craig (arktisvogel) in den unrsprünglich von mir stammenden Text eingebaut - ich glaube ohne klare Kennzeichnung...

Grundsätzlich würde ich - glaube ich - die ganze Passage zu EMACS entfernen, denn wir ...
(a) haben uns auf latexstudio festgelegt
(b) schreiben kein Buch über Editoren.

Wie seht Ihr das?

**Comment by baem2** [comment]
Ich würde da tendenziell zustimmen ...

Siehe #26

**Comment by LukasCBossert** [comment]
Ich stimme auch zu. Emacs waren/sind mir immer suspekt.

**Comment by sieversMartin** [comment]
Kann aus meiner Sicht geschlossen werden.
