### ISSUE TITLE
Stammbäume u.ä.

### ISSUE THREAD

**Issue by thomas-hilarius-meyer** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#9]
Noch ein Thema, das mir auf dem Magen liegt:

Wer kennt sich mit dem Zeichnen von Stammbäumen aus?
Diese Baumstrukturen verweigen sich ja in beide Richtungen komplex.
Gibt es dafür ein Spezialpaket?
Mag jemand den Abschnitt übernehmen?

Zu der im Skript vorgeschlagenen ersten, "dreckigen" Lösung, Open Office o.ä. zu nehmen und die Grafik einzubinden, stehe ich im Sinne eines schnellen Tipps immer noch, aber es sollte nicht die einzige Lösung sein...

**Comment by thomas-hilarius-meyer** [comment]
Hier:
https://upload.wikimedia.org/wikipedia/commons/4/46/Stammtafel_der_Karolinger.jpg
ist übrigens noch eine wundervolle Illustration zum Thema Stammbäume.
Die muss rein.

**Comment by baem2** [comment]
Mit tikz geht ein Stemma schon ganz gut:
```
\usepackage{tikz}
\usetikzlibrary{shapes}

...

\begin{tikzpicture} %[scale=0.9]
\tikzstyle{conjecture}=[ellipse,draw,dashed]
	\node[conjecture] {w} [sibling distance=4cm]
		child { node{F}}
		child { node[conjecture] {\emph{l}}
			child { node{V} [sibling distance=1.75cm]
				child { node{O}
					child { node{R}}
					}
				child { node{\emph{l}}
					child { node{\emph{l\textsubscript{B}}}}
					}
				}
			child { node{M} [sibling distance=1.75cm]
				child { node {G\textsubscript{1}}}
				child { node {G\textsubscript{2}}}
				child { node {\emph{a}}}
				}
		}
		child { node{\s}}
		child { node{P}
			child { node{\emph{k}}}
		}
	;
\end{tikzpicture}
```

Lukas kennt sich damit besser aus als ich, es gibt da gute und einfachere Pakete, dreckige Lösungen werden nicht benötigt ...

**Comment by LukasCBossert** [comment]
Das Paket `forest` ist an sich sehr gut. Für richtige Stammbäume gibt es `\usepackage[all]{genealogytree}` was aber auch gar nicht sooo einfach ist. 
`forest` ist ein sehr gutes tool für verschiedene Schemata.

**Comment by thomas-hilarius-meyer** [comment]
Dankeschön,
auf Wiedersehn #9
