### ISSUE TITLE
Gedichte im Inhaltsverzeichnis

### ISSUE THREAD

**Issue by AKielhorn** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#91]
Die Titel der Gedichte erscheinen im Inhaltsverzeichnis.

Das sieht irgendwie komisch aus, vor allem die "Würde der Frauen".

Sollte das nicht besser ein \poemtitle* sein?
Oder wenn nicht, dann ein \poemtoc als subsection?

**Comment by thomas-hilarius-meyer** [comment]
Also, ich denke, dass das noch erledigt werden muss:
Die Gedichte haben im Inhaltsverzeichnis natürlich nix verloren - also muss man in den Beispielen im Lyrik-Kapitel ändern...

**Comment by AKielhorn** [comment]
Ist geändert.
