### ISSUE TITLE
Von Markdown mit pandoc zu pdf (via Latex)

### ISSUE THREAD

**Issue by ottosmops** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#93]
Workflow und Einrichtung waeren evtl. einen Abschnitt wert.

**Comment by thomas-hilarius-meyer** [comment]
Ehrlich gesagt, weiß ich nicht genau, was das heißt...

Aber: in dubio pro reo - also meinerseits: "Hau rein"...

Was sagen die werten Kollegen?

----

PS: Ich hoffe, dass ich in den nächsten Monaten etwas mehr Zeit für LFGW habe!
Das soll jetzt raus. Wie stehts bei Euch?

**Comment by ottosmops** [comment]
Sorry für die Knappheit: gemeint ist ein Workflow, den wohl auch einer der Kollegen in seiner Bio beschreibt: 
* Schreiben des Textes mit Markdown
* Umwandeln mit pandoc zu PDF umwandeln (wobei pandoc Latex benutzt)
* die verwendete Latex-Vorlage, kann man nach den eigenen Wünschen anpassen; auch kann man Variabeln in YAML setzen
* dann kann man noch einen Schritt weitergehen und in einem Editor wie Sublime Text die Kompilierung projektspezifisch einrichten, d.h. z.B. ein kleines Script verwenden, das die Dateien und Optionen zusammenstellt (ist dies auch mit Atom möglich?); diese Kompilierung wird mit einer Tastenkombination gestartet
* mit einem PDF-Viewer wie Skim kann man das PDF automatisch aktualisieren. 

Bei mir läuft das soweit, aber ich bin kein Experte. Deshalb ist es nur eine Anregung/Vorschlag und ich würde gerne sehen, welche Optionen ich noch hätte.

Aus meiner Sicht hat der Workflow Vorteile: Man arbeitet in dem vergleichsweise einfachen und sauberen Format wie Markdown, das für kleinere Notizen, Exzerpte, Konzepte sehr gut geeignet ist. Markdown kann einerseits in vielen Anwendungen direkt weiterverwendet werden (Wiki, Blog) oder mit pandoc in verschiedenste Formate transformiert werden. Auch git kann ohne Einschränkung verwendet werden.

**Comment by baem2** [comment]
Markdown: Falls sich jemand findet, der das mal eben schreibt -- sehr gerne. Ansonsten würde ich es eher weglassen: Die wenigsten von Word/OO kommenden GeisteswissenschaftlerInnen werden erst noch schnell Markdown lernen wollen. Wir sind sowieso schon auf dem besten Wege, Leute durch die vielen Auswahlmöglichkeiten etc. mit unserem Buch eher vom Umstieg abzuschrecken.

> PS: Ich hoffe, dass ich in den nächsten Monaten etwas mehr Zeit für LFGW habe!
> Das soll jetzt raus. Wie stehts bei Euch?

Siehe hier: #63. Generell würde ich sagen, daß wir eher mal schauen sollten, das Paket zuzuschnüren, als noch weitere Fässer aufzumachen

**Comment by AKielhorn** [comment]
Ich schreibe seit 2011 vorwiegend markdown und konvertiere das dann in andere Formate, LaTeX ist nur eins davon.

Zu diesem Thema gibt es bereits ein gutes Buch:
Das ZEN von Pandoc
von Jan Ulrich Hasecke

Für einfache Texte ist das eine gute Wahl,
aber die hier behandelten Themen gehen weit über die Fähigkeiten von markdown hinaus.

Disclaimer: Ich habe bei dem Buch Korrektur gelesen.
