### ISSUE TITLE
Kritische Edition: TEI <-> Latex

### ISSUE THREAD

**Issue by ottosmops** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#94]
Vorschlag: Im Kapitel zum kritischen Apparat noch etwas zu den Konversionsmöglichkeiten von TEI und nach TEI zu ergänzen. Wie macht man das? Wie gut funktioniert es? Was ist zu beachten?

**Comment by thomas-hilarius-meyer** [comment]
Ich bin dafür!

**Comment by sieversMartin** [comment]
Von mir auch ein "Daumen hoch". TEI ist in den (digitalen) Geisteswissenschaften nicht mehr wegzudenken. Ein etablierter Workflow für gedruckte Publikationen existiert aber nicht. TeX kann hier sehr gute Dienste leisten.

**Comment by baem2** [comment]
Wenn Du das machen willst, kannst Du gerne dort ein Unterkapitel einfügen, TEI ist ja mittlerweile ziemlich etabliert.

Das würde ich aber klar getrennt von der Möglichkeit ohne TEI lassen, damit deutlich wird, daß TEI eine zusätzliche Option ist und man seine Edition auch auf dem einfachen Weg für den Druck fertig bekommt. (Wenn man nämlich nur auf den Druck zielt, etwa bei einer Diss, und die Mittel für online-Editionen o.ä. nicht zur Verfügung stehen, ist TEI too much. Man kann froh sein, wenn die Leute erstmal LaTeX lernen, TEI kann dann immer noch kommen.)

**Comment by ottosmops** [comment]
Vermutlich bin ich nicht der Richtige für das Schreiben: aber ich würde das Unterkapitel lesen wollen. Ansonsten sorry: Ich habe nicht gesehen, dass das Projekt eigentlich am Abschluss ist. 

@baem2 : Gibt es nicht in Deinem Dante Artikel einen Hinweis auf die Konvertierung von Latex to TEI? 

Bei uns in der Schweiz wird vom Nationalfonds aus auf digitale Publikationsformen gesetzt. Bei Editionsprojekten ist dann die Erzeugung von PDFs eher nicht ausreichend. Insofern ist auch bei einer Diss, wenn sie hauptsächlich aus einer Edition besteht, der Einsatz von TEI o.ä. zu überlegen. Mit TEI-Publisher, TEI-Boilerplate  und ähnlichen Tools sind einfache Visualisierungen im Web mit vergleichsweise wenig Aufwand möglich. TEI-Publisher bietet die Möglichkeit der Konvertierung via Latex. Aber ich weiss nicht wie es mit dem kritischem Apparat aussieht. Das funktioniert evtl. (noch) nicht.

vgl. auch Marjorie Burghart in http://jtei.revues.org/1520 

"I am preparing a generic TEI-to-LaTeX and TEI-to-PDF conversion feature that will be implemented in the Critical Apparatus Toolbox. I chose LaTeX as an intermediary format because it offers all the desired options, thanks to the reledmac package especially designed for typesetting critical editions.17 It is better suited to the specific needs of critical editions than XSL:FO. Another advantage of an intermediary file is that it leaves users the opportunity to edit the LaTeX code to obtain a better PDF result, which they might prefer over a modification of the XSLT templates, depending on their skillset." mit Verweis auf das reledmac Paket

**Comment by baem2** [comment]
Ja, den Verweis auf TEI kann ich gerne einfügen, das ist kein Problem.

Meines Wissens ist es bislang nicht ganz unproblematisch, von TEI zu einer druckbaren pdf zu kommen (bzw. man muß sich seinen Weg halt selbst "machen"). Klar, vom Nationalfonds gesponsorte Projekte haben natürlich auch das Geld, einen solchen Weg zu bahnen ... (ähnlich in Deutschland: ediarum der BBAW [aktuelle Komödie S. 32]) und den Webspace etc. für die Online-Darstellung mittelfristig zu bezahlen. Bei kleineren Editionsvorhaben ist man aber froh, wenn überhaupt irgendwann ein Buch da ist, und an Webseiten ist gar nicht zu denken: Der zusätzliche Aufwand ist einfach zu hoch ...

Gerade in langfristiger Perspektive ist es in jedem Fall sinnvoll, auf TEI zu setzen, das ist keine Frage.
