### ISSUE TITLE
TeX Live 2016 oder 2017

### ISSUE THREAD

**Issue by UweZiegenhagen** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#95]
2017 ist grad erschienen, ich würde es aber auf meinem "Serverchen" bei 2016 belassen.

**Comment by baem2** [comment]
Als alter debian-Nutzer kann ich nur sagen: Jo. Never change a running system ;)

**Comment by LukasCBossert** [comment]
auch wenn ich privat umsteigen werde, besteht für unser Projekt kein Zwang für  TL2017.

**Comment by UweZiegenhagen** [comment]
Ich habe jetzt auf allen Maschinen TeXLive 2017 am Start, gab keine Probleme.
