### ISSUE TITLE
Zitieren von Archivquellen

### ISSUE THREAD

**Issue by simifilm** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#98]
Dieses "Issue" hat nicht direkt etwas mit dem Projekt zu tun, aber ich poste es dennoch, weil ich denke, dass hier viel geisteswissenschaftliche und LaTeX-Kompetenz versammelt ist, und die Diskussion deshalb konzentrierter und fruchtbarer ausfallen dürfte als in einem allgemeinen LaTeX-Forum. Falls Ihr das Thema aber unpassend findet, gebt Bescheid, dann poste ich es an einem anderen Ort.

Folgende Situation: Da ich in meinem aktuellen Forschungsprojekt erstmals Archivquellen zitieren muss, bin ich dabei, `biblatex-fiwi` um einen entsprechenden Dokumenttyp zu erweitern. `biblatex` bietet von Haus aus nur den Typ `unpublished`, und soweit ich gesehen habe, hat einzig `biblatex-chicago` spezifische Anpassungen für Archivalien. Die scheinen mir aber recht umständlich (wobei ich hier aber nicht allzu gründlich nachgelesen habe). 

Ich habe mich dazu entschieden, den Dokumenttypus `archival` einzuführen, der die Felder `library` (bereits in `biblatex` enthalten) und `librarylocation` bietet.

Typische Einträge sehen so aus:

```
@archival{Heinemann.S:1976a,
	Author = {Heinemann, S.},
	Date = {1976-01-07},
	Library = {BArch},
	Librarylocation = {DR 117/17769},
	Title = {Aktennotiz über die Vorführung der Discofilme am 9. 12. 1975},
	Year = {1976}}

@archival{AG-Filmbeschaffung:1971a,
	Author = {{AG Filmbeschaffung}},
	Date = {1971-07-04},
	Library = {BArch},
	Librarylocation = {DR 117/25997},
	Title = {Referat zur Direktionssitzung am 7.4.1971},
	Year = {1971}}

```
Das gibt dann folgende Bibliografieeinträge:

AG Filmbeschaffung (1971): _Referat zur Direktionssitzung am 7.4.1971._ 4. Juli 1971. BArch DR 117/25997.

Heinemann, S. (1976): _Aktennotiz über die Vorführung der Discofilme am 9. 12. 1975._ 7. Januar 1976. BArch DR 117/17769.

Das ist alles nur vorläufig, falls jemand gute Argumente bringt, warum man das besser anders machen sollte, passe ich das gerne an. Da ich normalerweise nicht mit Archivquellen arbeite, habe ich diesbezüglich nicht viel Erfahrung, kenne also nicht alle Spezialfälle und bin entsprechend um jeden Hinweis froh.

Ich bin auch um Hinweise dankbar, wie man mit Akten umgehen soll, die keinen klaren Autor und/oder Titel aufweisen; vor allem bei der Frage, wie diese im Text zitiert werden sollen. Momentan benutze ich – wie auch sonst in `biblatex-fiwi` – das "Nachname-Jahr"-Schema.

**Comment by baem2** [comment]
Sorry, da konnten wir dir wohl nicht weiterhelfen (du siehst ja, hier ist ohnehin nicht viel los). Vielleicht hast du woanders Hilfe gefunden?

Ich mache hier mal zu.
