### ISSUE TITLE
Zugang für  lhumb

### ISSUE THREAD

**Issue by UweZiegenhagen** [thomas-hilarius-meyer/LaTeX-fuer-Geisteswissenschaftler#99]
Hi zusammen,

könnte jemand bitte User " lhumb" einrichten. Ist Professort Humbert aus Wuppertal, der einige Fixes hat. 

Uwe

**Comment by baem2** [comment]
Ich denke, der einzige, der das kann, ist @thomas-hilarius-meyer

**Comment by thomas-hilarius-meyer** [comment]
Upsi, bin ich so mächtig... ;-)

Dann werd ichs mal gleich versuchen!

Am 23. September 2017 um 13:58 schrieb Philipp <notifications@github.com>:

**Comment by thomas-hilarius-meyer** [comment]
Schon passiert....

Wenn das Buch fertig machen auch so schnell ginge...

Am 23. September 2017 um 14:50 schrieb Thomas Hilarius Meyer <
thomas.hilarius.meyer@gmail.com>:

**Comment by lhumb** [comment]
Lieben Dank -- habe meine kleinen Änderungen soeben eingecheckt ;-)

**Comment by baem2** [comment]
Danke!
